<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LgaCoordinatesSeeder extends Seeder
{
    public function run(): void
    {
        $lgas = [
            // ----------------------------------------------------------------
            // ABIA
            // ----------------------------------------------------------------
            ['state' => 'Abia', 'lga' => 'Aba North',        'latitude' =>  5.1065, 'longitude' =>  7.3666],
            ['state' => 'Abia', 'lga' => 'Aba South',        'latitude' =>  5.0833, 'longitude' =>  7.3667],
            ['state' => 'Abia', 'lga' => 'Arochukwu',        'latitude' =>  5.3833, 'longitude' =>  7.9000],
            ['state' => 'Abia', 'lga' => 'Bende',            'latitude' =>  5.5167, 'longitude' =>  7.6333],
            ['state' => 'Abia', 'lga' => 'Ikwuano',          'latitude' =>  5.2833, 'longitude' =>  7.5167],
            ['state' => 'Abia', 'lga' => 'Isiala Ngwa North','latitude' =>  5.2167, 'longitude' =>  7.2833],
            ['state' => 'Abia', 'lga' => 'Isiala Ngwa South','latitude' =>  5.1500, 'longitude' =>  7.2500],
            ['state' => 'Abia', 'lga' => 'Isuikwuato',       'latitude' =>  5.7333, 'longitude' =>  7.5833],
            ['state' => 'Abia', 'lga' => 'Obi Ngwa',         'latitude' =>  5.1667, 'longitude' =>  7.3333],
            ['state' => 'Abia', 'lga' => 'Ohafia',           'latitude' =>  5.6167, 'longitude' =>  7.8333],
            ['state' => 'Abia', 'lga' => 'Osisioma',         'latitude' =>  5.1167, 'longitude' =>  7.3000],
            ['state' => 'Abia', 'lga' => 'Ugwunagbo',        'latitude' =>  4.9833, 'longitude' =>  7.2333],
            ['state' => 'Abia', 'lga' => 'Ukwa East',        'latitude' =>  4.9167, 'longitude' =>  7.1667],
            ['state' => 'Abia', 'lga' => 'Ukwa West',        'latitude' =>  4.9000, 'longitude' =>  7.0667],
            ['state' => 'Abia', 'lga' => 'Umuahia North',    'latitude' =>  5.5333, 'longitude' =>  7.4833],
            ['state' => 'Abia', 'lga' => 'Umuahia South',    'latitude' =>  5.5000, 'longitude' =>  7.4500],
            ['state' => 'Abia', 'lga' => 'Umu Nneochi',      'latitude' =>  5.7000, 'longitude' =>  7.4333],

            // ----------------------------------------------------------------
            // ADAMAWA
            // ----------------------------------------------------------------
            ['state' => 'Adamawa', 'lga' => 'Demsa',         'latitude' =>  8.8667, 'longitude' => 12.2833],
            ['state' => 'Adamawa', 'lga' => 'Fufure',        'latitude' =>  9.8000, 'longitude' => 12.7667],
            ['state' => 'Adamawa', 'lga' => 'Ganye',         'latitude' =>  8.4333, 'longitude' => 12.0500],
            ['state' => 'Adamawa', 'lga' => 'Gayuk',         'latitude' =>  9.5167, 'longitude' => 12.6667],
            ['state' => 'Adamawa', 'lga' => 'Gombi',         'latitude' =>  9.9333, 'longitude' => 12.7333],
            ['state' => 'Adamawa', 'lga' => 'Grie',          'latitude' =>  9.1333, 'longitude' => 12.4000],
            ['state' => 'Adamawa', 'lga' => 'Hong',          'latitude' => 10.2667, 'longitude' => 12.9000],
            ['state' => 'Adamawa', 'lga' => 'Jada',          'latitude' =>  8.7667, 'longitude' => 11.8833],
            ['state' => 'Adamawa', 'lga' => 'Lamurde',       'latitude' =>  9.0333, 'longitude' => 12.3000],
            ['state' => 'Adamawa', 'lga' => 'Madagali',      'latitude' => 10.8833, 'longitude' => 13.5833],
            ['state' => 'Adamawa', 'lga' => 'Maiha',         'latitude' => 10.2333, 'longitude' => 13.2667],
            ['state' => 'Adamawa', 'lga' => 'Mayo Belwa',    'latitude' =>  8.5333, 'longitude' => 11.8833],
            ['state' => 'Adamawa', 'lga' => 'Michika',       'latitude' => 10.6167, 'longitude' => 13.3833],
            ['state' => 'Adamawa', 'lga' => 'Mubi North',    'latitude' => 10.2667, 'longitude' => 13.2667],
            ['state' => 'Adamawa', 'lga' => 'Mubi South',    'latitude' => 10.2000, 'longitude' => 13.2500],
            ['state' => 'Adamawa', 'lga' => 'Numan',         'latitude' =>  9.4667, 'longitude' => 12.0333],
            ['state' => 'Adamawa', 'lga' => 'Shelleng',      'latitude' =>  9.7500, 'longitude' => 12.3000],
            ['state' => 'Adamawa', 'lga' => 'Song',          'latitude' =>  9.8167, 'longitude' => 12.9167],
            ['state' => 'Adamawa', 'lga' => 'Toungo',        'latitude' =>  8.1167, 'longitude' => 11.8667],
            ['state' => 'Adamawa', 'lga' => 'Yola North',    'latitude' =>  9.2035, 'longitude' => 12.4954],
            ['state' => 'Adamawa', 'lga' => 'Yola South',    'latitude' =>  9.1667, 'longitude' => 12.5000],

            // ----------------------------------------------------------------
            // AKWA IBOM
            // ----------------------------------------------------------------
            ['state' => 'Akwa Ibom', 'lga' => 'Abak',               'latitude' =>  4.9833, 'longitude' =>  7.7833],
            ['state' => 'Akwa Ibom', 'lga' => 'Eastern Obolo',      'latitude' =>  4.5167, 'longitude' =>  7.6500],
            ['state' => 'Akwa Ibom', 'lga' => 'Eket',               'latitude' =>  4.6333, 'longitude' =>  7.9167],
            ['state' => 'Akwa Ibom', 'lga' => 'Esit Eket',          'latitude' =>  4.5833, 'longitude' =>  7.9833],
            ['state' => 'Akwa Ibom', 'lga' => 'Essien Udim',        'latitude' =>  5.0833, 'longitude' =>  7.8500],
            ['state' => 'Akwa Ibom', 'lga' => 'Etim Ekpo',          'latitude' =>  5.0000, 'longitude' =>  7.7167],
            ['state' => 'Akwa Ibom', 'lga' => 'Etinan',             'latitude' =>  4.9167, 'longitude' =>  7.8500],
            ['state' => 'Akwa Ibom', 'lga' => 'Ibeno',              'latitude' =>  4.5167, 'longitude' =>  7.9833],
            ['state' => 'Akwa Ibom', 'lga' => 'Ibesikpo Asutan',    'latitude' =>  4.8667, 'longitude' =>  7.9333],
            ['state' => 'Akwa Ibom', 'lga' => 'Ibiono Ibom',        'latitude' =>  5.2167, 'longitude' =>  7.9167],
            ['state' => 'Akwa Ibom', 'lga' => 'Ika',                'latitude' =>  4.6500, 'longitude' =>  7.8000],
            ['state' => 'Akwa Ibom', 'lga' => 'Ikono',              'latitude' =>  5.1667, 'longitude' =>  7.8000],
            ['state' => 'Akwa Ibom', 'lga' => 'Ikot Abasi',         'latitude' =>  4.5667, 'longitude' =>  7.5667],
            ['state' => 'Akwa Ibom', 'lga' => 'Ikot Ekpene',        'latitude' =>  5.1833, 'longitude' =>  7.7167],
            ['state' => 'Akwa Ibom', 'lga' => 'Ini',                'latitude' =>  5.3500, 'longitude' =>  7.8333],
            ['state' => 'Akwa Ibom', 'lga' => 'Itu',                'latitude' =>  5.2000, 'longitude' =>  8.0333],
            ['state' => 'Akwa Ibom', 'lga' => 'Mbo',                'latitude' =>  4.4833, 'longitude' =>  8.0500],
            ['state' => 'Akwa Ibom', 'lga' => 'Mkpat Enin',         'latitude' =>  4.7500, 'longitude' =>  7.6500],
            ['state' => 'Akwa Ibom', 'lga' => 'Nsit Atai',          'latitude' =>  5.0000, 'longitude' =>  7.9167],
            ['state' => 'Akwa Ibom', 'lga' => 'Nsit Ibom',          'latitude' =>  4.9167, 'longitude' =>  7.9833],
            ['state' => 'Akwa Ibom', 'lga' => 'Nsit Ubium',         'latitude' =>  4.8333, 'longitude' =>  7.9167],
            ['state' => 'Akwa Ibom', 'lga' => 'Obot Akara',         'latitude' =>  5.1000, 'longitude' =>  7.6833],
            ['state' => 'Akwa Ibom', 'lga' => 'Okobo',              'latitude' =>  4.6667, 'longitude' =>  8.1167],
            ['state' => 'Akwa Ibom', 'lga' => 'Onna',               'latitude' =>  4.7333, 'longitude' =>  7.9333],
            ['state' => 'Akwa Ibom', 'lga' => 'Oron',               'latitude' =>  4.8000, 'longitude' =>  8.2333],
            ['state' => 'Akwa Ibom', 'lga' => 'Oruk Anam',          'latitude' =>  4.8833, 'longitude' =>  7.5833],
            ['state' => 'Akwa Ibom', 'lga' => 'Udung Uko',          'latitude' =>  4.7000, 'longitude' =>  8.0500],
            ['state' => 'Akwa Ibom', 'lga' => 'Ukanafun',           'latitude' =>  4.9500, 'longitude' =>  7.6667],
            ['state' => 'Akwa Ibom', 'lga' => 'Uruan',              'latitude' =>  5.0667, 'longitude' =>  8.1167],
            ['state' => 'Akwa Ibom', 'lga' => 'Urue Offong/Oruko',  'latitude' =>  4.7833, 'longitude' =>  8.2167],
            ['state' => 'Akwa Ibom', 'lga' => 'Uyo',                'latitude' =>  5.0333, 'longitude' =>  7.9167],

            // ----------------------------------------------------------------
            // ANAMBRA
            // ----------------------------------------------------------------
            ['state' => 'Anambra', 'lga' => 'Aguata',          'latitude' =>  6.0167, 'longitude' =>  7.0833],
            ['state' => 'Anambra', 'lga' => 'Anambra East',    'latitude' =>  6.3833, 'longitude' =>  7.0167],
            ['state' => 'Anambra', 'lga' => 'Anambra West',    'latitude' =>  6.3167, 'longitude' =>  6.8833],
            ['state' => 'Anambra', 'lga' => 'Anaocha',         'latitude' =>  6.1333, 'longitude' =>  7.0500],
            ['state' => 'Anambra', 'lga' => 'Awka North',      'latitude' =>  6.2849, 'longitude' =>  7.0689],
            ['state' => 'Anambra', 'lga' => 'Awka South',      'latitude' =>  6.2093, 'longitude' =>  7.0731],
            ['state' => 'Anambra', 'lga' => 'Ayamelum',        'latitude' =>  6.5500, 'longitude' =>  6.9500],
            ['state' => 'Anambra', 'lga' => 'Dunukofia',       'latitude' =>  6.2167, 'longitude' =>  7.0167],
            ['state' => 'Anambra', 'lga' => 'Ekwusigo',        'latitude' =>  6.0500, 'longitude' =>  6.9167],
            ['state' => 'Anambra', 'lga' => 'Idemili North',   'latitude' =>  6.1333, 'longitude' =>  6.9833],
            ['state' => 'Anambra', 'lga' => 'Idemili South',   'latitude' =>  6.0833, 'longitude' =>  6.9667],
            ['state' => 'Anambra', 'lga' => 'Ihiala',          'latitude' =>  5.8500, 'longitude' =>  6.8500],
            ['state' => 'Anambra', 'lga' => 'Njikoka',         'latitude' =>  6.2167, 'longitude' =>  7.1167],
            ['state' => 'Anambra', 'lga' => 'Nnewi North',     'latitude' =>  6.0170, 'longitude' =>  6.9195],
            ['state' => 'Anambra', 'lga' => 'Nnewi South',     'latitude' =>  5.9667, 'longitude' =>  6.9333],
            ['state' => 'Anambra', 'lga' => 'Ogbaru',          'latitude' =>  5.9500, 'longitude' =>  6.7833],
            ['state' => 'Anambra', 'lga' => 'Onitsha North',   'latitude' =>  6.1484, 'longitude' =>  6.7924],
            ['state' => 'Anambra', 'lga' => 'Onitsha South',   'latitude' =>  6.1378, 'longitude' =>  6.7811],
            ['state' => 'Anambra', 'lga' => 'Orumba North',    'latitude' =>  5.9167, 'longitude' =>  7.1500],
            ['state' => 'Anambra', 'lga' => 'Orumba South',    'latitude' =>  5.8667, 'longitude' =>  7.1167],
            ['state' => 'Anambra', 'lga' => 'Oyi',             'latitude' =>  6.3833, 'longitude' =>  6.9833],

            // ----------------------------------------------------------------
            // BAUCHI
            // ----------------------------------------------------------------
            ['state' => 'Bauchi', 'lga' => 'Alkaleri',      'latitude' => 10.9167, 'longitude' => 10.9167],
            ['state' => 'Bauchi', 'lga' => 'Bauchi',        'latitude' => 10.3108, 'longitude' =>  9.8436],
            ['state' => 'Bauchi', 'lga' => 'Bogoro',        'latitude' =>  9.9667, 'longitude' =>  9.6167],
            ['state' => 'Bauchi', 'lga' => 'Damban',        'latitude' => 11.3500, 'longitude' => 10.5667],
            ['state' => 'Bauchi', 'lga' => 'Darazo',        'latitude' => 11.0000, 'longitude' => 10.4167],
            ['state' => 'Bauchi', 'lga' => 'Dass',          'latitude' => 10.2167, 'longitude' =>  9.6667],
            ['state' => 'Bauchi', 'lga' => 'Gamawa',        'latitude' => 12.1333, 'longitude' => 10.5333],
            ['state' => 'Bauchi', 'lga' => 'Ganjuwa',       'latitude' => 11.0333, 'longitude' =>  9.6167],
            ['state' => 'Bauchi', 'lga' => 'Giade',         'latitude' => 11.8667, 'longitude' => 10.7333],
            ['state' => 'Bauchi', 'lga' => 'Itas/Gadau',    'latitude' => 12.0000, 'longitude' => 10.6667],
            ['state' => 'Bauchi', 'lga' => "Jama'are",      'latitude' => 11.7833, 'longitude' => 11.1833],
            ['state' => 'Bauchi', 'lga' => 'Katagum',       'latitude' => 11.5833, 'longitude' => 10.9833],
            ['state' => 'Bauchi', 'lga' => 'Kirfi',         'latitude' => 10.6000, 'longitude' => 10.6667],
            ['state' => 'Bauchi', 'lga' => 'Misau',         'latitude' => 11.3333, 'longitude' => 10.9333],
            ['state' => 'Bauchi', 'lga' => 'Ningi',         'latitude' => 11.1000, 'longitude' =>  9.0167],
            ['state' => 'Bauchi', 'lga' => 'Shira',         'latitude' => 11.9833, 'longitude' => 10.4667],
            ['state' => 'Bauchi', 'lga' => 'Tafawa Balewa', 'latitude' =>  9.9167, 'longitude' =>  9.9667],
            ['state' => 'Bauchi', 'lga' => 'Toro',          'latitude' => 10.7833, 'longitude' =>  9.2167],
            ['state' => 'Bauchi', 'lga' => 'Warji',         'latitude' => 11.6333, 'longitude' => 10.2167],
            ['state' => 'Bauchi', 'lga' => 'Zaki',          'latitude' => 12.0667, 'longitude' => 10.8333],

            // ----------------------------------------------------------------
            // BAYELSA
            // ----------------------------------------------------------------
            ['state' => 'Bayelsa', 'lga' => 'Brass',           'latitude' =>  4.3167, 'longitude' =>  6.2333],
            ['state' => 'Bayelsa', 'lga' => 'Ekeremor',        'latitude' =>  4.7167, 'longitude' =>  5.9500],
            ['state' => 'Bayelsa', 'lga' => 'Kolokuma/Opokuma','latitude' =>  4.9333, 'longitude' =>  6.2500],
            ['state' => 'Bayelsa', 'lga' => 'Nembe',           'latitude' =>  4.5000, 'longitude' =>  6.4167],
            ['state' => 'Bayelsa', 'lga' => 'Ogbia',           'latitude' =>  4.8833, 'longitude' =>  6.4833],
            ['state' => 'Bayelsa', 'lga' => 'Sagbama',         'latitude' =>  5.1000, 'longitude' =>  6.0833],
            ['state' => 'Bayelsa', 'lga' => 'Southern Ijaw',   'latitude' =>  4.3833, 'longitude' =>  5.8333],
            ['state' => 'Bayelsa', 'lga' => 'Yenagoa',         'latitude' =>  4.9247, 'longitude' =>  6.2642],

            // ----------------------------------------------------------------
            // BENUE
            // ----------------------------------------------------------------
            ['state' => 'Benue', 'lga' => 'Ado',           'latitude' =>  7.6333, 'longitude' =>  8.6167],
            ['state' => 'Benue', 'lga' => 'Agatu',         'latitude' =>  7.7167, 'longitude' =>  7.9833],
            ['state' => 'Benue', 'lga' => 'Apa',           'latitude' =>  7.3500, 'longitude' =>  8.0167],
            ['state' => 'Benue', 'lga' => 'Buruku',        'latitude' =>  7.7833, 'longitude' =>  9.2000],
            ['state' => 'Benue', 'lga' => 'Gboko',         'latitude' =>  7.3167, 'longitude' =>  9.0000],
            ['state' => 'Benue', 'lga' => 'Guma',          'latitude' =>  7.7833, 'longitude' =>  8.6833],
            ['state' => 'Benue', 'lga' => 'Gwer East',     'latitude' =>  7.5000, 'longitude' =>  8.8667],
            ['state' => 'Benue', 'lga' => 'Gwer West',     'latitude' =>  7.5667, 'longitude' =>  8.6333],
            ['state' => 'Benue', 'lga' => 'Katsina-Ala',   'latitude' =>  7.1667, 'longitude' =>  9.2833],
            ['state' => 'Benue', 'lga' => 'Konshisha',     'latitude' =>  6.9500, 'longitude' =>  9.2667],
            ['state' => 'Benue', 'lga' => 'Kwande',        'latitude' =>  6.8667, 'longitude' =>  9.1000],
            ['state' => 'Benue', 'lga' => 'Logo',          'latitude' =>  7.0333, 'longitude' =>  9.4333],
            ['state' => 'Benue', 'lga' => 'Makurdi',       'latitude' =>  7.7314, 'longitude' =>  8.5370],
            ['state' => 'Benue', 'lga' => 'Obi',           'latitude' =>  7.4833, 'longitude' =>  8.3167],
            ['state' => 'Benue', 'lga' => 'Ogbadibo',      'latitude' =>  7.2500, 'longitude' =>  7.7167],
            ['state' => 'Benue', 'lga' => 'Ohimini',       'latitude' =>  7.3167, 'longitude' =>  7.6667],
            ['state' => 'Benue', 'lga' => 'Oju',           'latitude' =>  6.9833, 'longitude' =>  8.3167],
            ['state' => 'Benue', 'lga' => 'Okpokwu',       'latitude' =>  7.1333, 'longitude' =>  7.9167],
            ['state' => 'Benue', 'lga' => 'Oturkpo',       'latitude' =>  7.1667, 'longitude' =>  8.1333],
            ['state' => 'Benue', 'lga' => 'Tarka',         'latitude' =>  7.1167, 'longitude' =>  9.0833],
            ['state' => 'Benue', 'lga' => 'Ukum',          'latitude' =>  7.0333, 'longitude' =>  9.6333],
            ['state' => 'Benue', 'lga' => 'Ushongo',       'latitude' =>  7.1667, 'longitude' =>  9.1167],
            ['state' => 'Benue', 'lga' => 'Vandeikya',     'latitude' =>  6.8333, 'longitude' =>  9.3833],

            // ----------------------------------------------------------------
            // BORNO
            // ----------------------------------------------------------------
            ['state' => 'Borno', 'lga' => 'Abadam',        'latitude' => 13.8667, 'longitude' => 12.8167],
            ['state' => 'Borno', 'lga' => 'Askira/Uba',    'latitude' => 10.4667, 'longitude' => 13.0000],
            ['state' => 'Borno', 'lga' => 'Bama',          'latitude' => 11.5167, 'longitude' => 13.6833],
            ['state' => 'Borno', 'lga' => 'Bayo',          'latitude' => 10.2167, 'longitude' => 12.5667],
            ['state' => 'Borno', 'lga' => 'Biu',           'latitude' => 10.6167, 'longitude' => 12.1917],
            ['state' => 'Borno', 'lga' => 'Chibok',        'latitude' => 10.8500, 'longitude' => 12.8500],
            ['state' => 'Borno', 'lga' => 'Damboa',        'latitude' => 11.1667, 'longitude' => 12.7000],
            ['state' => 'Borno', 'lga' => 'Dikwa',         'latitude' => 12.0333, 'longitude' => 13.9167],
            ['state' => 'Borno', 'lga' => 'Gubio',         'latitude' => 12.6333, 'longitude' => 13.3667],
            ['state' => 'Borno', 'lga' => 'Guzamala',      'latitude' => 12.8167, 'longitude' => 12.6667],
            ['state' => 'Borno', 'lga' => 'Gwoza',         'latitude' => 10.9000, 'longitude' => 13.6833],
            ['state' => 'Borno', 'lga' => 'Hawul',         'latitude' => 10.3500, 'longitude' => 12.2833],
            ['state' => 'Borno', 'lga' => 'Jere',          'latitude' => 11.7500, 'longitude' => 13.1833],
            ['state' => 'Borno', 'lga' => 'Kaga',          'latitude' => 12.4833, 'longitude' => 13.4833],
            ['state' => 'Borno', 'lga' => 'Kala/Balge',    'latitude' => 12.5000, 'longitude' => 14.2833],
            ['state' => 'Borno', 'lga' => 'Konduga',       'latitude' => 11.6333, 'longitude' => 13.4333],
            ['state' => 'Borno', 'lga' => 'Kukawa',        'latitude' => 12.9167, 'longitude' => 13.5833],
            ['state' => 'Borno', 'lga' => 'Kwaya Kusar',   'latitude' => 10.4333, 'longitude' => 12.6333],
            ['state' => 'Borno', 'lga' => 'Mafa',          'latitude' => 12.0167, 'longitude' => 13.6500],
            ['state' => 'Borno', 'lga' => 'Magumeri',      'latitude' => 12.1167, 'longitude' => 12.8167],
            ['state' => 'Borno', 'lga' => 'Maiduguri',     'latitude' => 11.8333, 'longitude' => 13.1500],
            ['state' => 'Borno', 'lga' => 'Marte',         'latitude' => 12.3667, 'longitude' => 13.7833],
            ['state' => 'Borno', 'lga' => 'Mobbar',        'latitude' => 13.5000, 'longitude' => 13.2333],
            ['state' => 'Borno', 'lga' => 'Monguno',       'latitude' => 12.6833, 'longitude' => 13.6000],
            ['state' => 'Borno', 'lga' => 'Ngala',         'latitude' => 12.3500, 'longitude' => 14.2167],
            ['state' => 'Borno', 'lga' => 'Nganzai',       'latitude' => 12.3000, 'longitude' => 13.2000],
            ['state' => 'Borno', 'lga' => 'Shani',         'latitude' => 10.2333, 'longitude' => 12.0333],

            // ----------------------------------------------------------------
            // CROSS RIVER
            // ----------------------------------------------------------------
            ['state' => 'Cross River', 'lga' => 'Abi',              'latitude' =>  5.9833, 'longitude' =>  8.3000],
            ['state' => 'Cross River', 'lga' => 'Akamkpa',          'latitude' =>  5.3500, 'longitude' =>  8.3500],
            ['state' => 'Cross River', 'lga' => 'Akpabuyo',         'latitude' =>  4.9667, 'longitude' =>  8.4167],
            ['state' => 'Cross River', 'lga' => 'Bakassi',          'latitude' =>  4.6500, 'longitude' =>  8.6667],
            ['state' => 'Cross River', 'lga' => 'Bekwarra',         'latitude' =>  6.6500, 'longitude' =>  9.0500],
            ['state' => 'Cross River', 'lga' => 'Biase',            'latitude' =>  5.3667, 'longitude' =>  8.1333],
            ['state' => 'Cross River', 'lga' => 'Boki',             'latitude' =>  6.1667, 'longitude' =>  9.0833],
            ['state' => 'Cross River', 'lga' => 'Calabar Municipal','latitude' =>  4.9500, 'longitude' =>  8.3333],
            ['state' => 'Cross River', 'lga' => 'Calabar South',    'latitude' =>  4.9333, 'longitude' =>  8.3167],
            ['state' => 'Cross River', 'lga' => 'Etung',            'latitude' =>  5.8833, 'longitude' =>  9.1333],
            ['state' => 'Cross River', 'lga' => 'Ikom',             'latitude' =>  5.9667, 'longitude' =>  8.7167],
            ['state' => 'Cross River', 'lga' => 'Obanliku',         'latitude' =>  6.5167, 'longitude' =>  9.1667],
            ['state' => 'Cross River', 'lga' => 'Obubra',           'latitude' =>  5.9667, 'longitude' =>  8.3167],
            ['state' => 'Cross River', 'lga' => 'Obudu',            'latitude' =>  6.6667, 'longitude' =>  9.1667],
            ['state' => 'Cross River', 'lga' => 'Odukpani',         'latitude' =>  5.1167, 'longitude' =>  8.2500],
            ['state' => 'Cross River', 'lga' => 'Ogoja',            'latitude' =>  6.6500, 'longitude' =>  8.8000],
            ['state' => 'Cross River', 'lga' => 'Yakuur',           'latitude' =>  5.8167, 'longitude' =>  8.3667],
            ['state' => 'Cross River', 'lga' => 'Yala',             'latitude' =>  6.9333, 'longitude' =>  8.8167],

            // ----------------------------------------------------------------
            // DELTA
            // ----------------------------------------------------------------
            ['state' => 'Delta', 'lga' => 'Aniocha North',  'latitude' =>  6.3167, 'longitude' =>  6.6833],
            ['state' => 'Delta', 'lga' => 'Aniocha South',  'latitude' =>  6.2167, 'longitude' =>  6.6833],
            ['state' => 'Delta', 'lga' => 'Bomadi',         'latitude' =>  5.3667, 'longitude' =>  5.9167],
            ['state' => 'Delta', 'lga' => 'Burutu',         'latitude' =>  5.3500, 'longitude' =>  5.5167],
            ['state' => 'Delta', 'lga' => 'Ethiope East',   'latitude' =>  5.7333, 'longitude' =>  6.1333],
            ['state' => 'Delta', 'lga' => 'Ethiope West',   'latitude' =>  5.6500, 'longitude' =>  5.9167],
            ['state' => 'Delta', 'lga' => 'Ika North East', 'latitude' =>  6.0833, 'longitude' =>  6.3667],
            ['state' => 'Delta', 'lga' => 'Ika South',      'latitude' =>  5.9333, 'longitude' =>  6.3500],
            ['state' => 'Delta', 'lga' => 'Isoko North',    'latitude' =>  5.4167, 'longitude' =>  6.2667],
            ['state' => 'Delta', 'lga' => 'Isoko South',    'latitude' =>  5.2833, 'longitude' =>  6.2333],
            ['state' => 'Delta', 'lga' => 'Ndokwa East',    'latitude' =>  5.6500, 'longitude' =>  6.5833],
            ['state' => 'Delta', 'lga' => 'Ndokwa West',    'latitude' =>  5.6500, 'longitude' =>  6.3667],
            ['state' => 'Delta', 'lga' => 'Okpe',           'latitude' =>  5.5667, 'longitude' =>  5.9833],
            ['state' => 'Delta', 'lga' => 'Oshimili North', 'latitude' =>  6.2833, 'longitude' =>  6.7333],
            ['state' => 'Delta', 'lga' => 'Oshimili South', 'latitude' =>  6.1833, 'longitude' =>  6.7500],
            ['state' => 'Delta', 'lga' => 'Patani',         'latitude' =>  5.5667, 'longitude' =>  6.0833],
            ['state' => 'Delta', 'lga' => 'Sapele',         'latitude' =>  5.8833, 'longitude' =>  5.6833],
            ['state' => 'Delta', 'lga' => 'Udu',            'latitude' =>  5.6500, 'longitude' =>  5.8167],
            ['state' => 'Delta', 'lga' => 'Ughelli North',  'latitude' =>  5.5000, 'longitude' =>  6.0000],
            ['state' => 'Delta', 'lga' => 'Ughelli South',  'latitude' =>  5.3833, 'longitude' =>  6.0000],
            ['state' => 'Delta', 'lga' => 'Ukwuani',        'latitude' =>  5.8167, 'longitude' =>  6.4167],
            ['state' => 'Delta', 'lga' => 'Uvwie',          'latitude' =>  5.6167, 'longitude' =>  5.8000],
            ['state' => 'Delta', 'lga' => 'Warri North',    'latitude' =>  5.7833, 'longitude' =>  5.5500],
            ['state' => 'Delta', 'lga' => 'Warri South',    'latitude' =>  5.5167, 'longitude' =>  5.7500],
            ['state' => 'Delta', 'lga' => 'Warri South West','latitude' =>  5.4833, 'longitude' =>  5.6167],

            // ----------------------------------------------------------------
            // EBONYI
            // ----------------------------------------------------------------
            ['state' => 'Ebonyi', 'lga' => 'Abakaliki',     'latitude' =>  6.3249, 'longitude' =>  8.1137],
            ['state' => 'Ebonyi', 'lga' => 'Afikpo North',  'latitude' =>  5.8833, 'longitude' =>  7.9333],
            ['state' => 'Ebonyi', 'lga' => 'Afikpo South',  'latitude' =>  5.8167, 'longitude' =>  7.9500],
            ['state' => 'Ebonyi', 'lga' => 'Ebonyi',        'latitude' =>  6.2167, 'longitude' =>  8.0500],
            ['state' => 'Ebonyi', 'lga' => 'Ezza North',    'latitude' =>  6.4833, 'longitude' =>  8.1333],
            ['state' => 'Ebonyi', 'lga' => 'Ezza South',    'latitude' =>  6.3500, 'longitude' =>  8.1833],
            ['state' => 'Ebonyi', 'lga' => 'Ikwo',          'latitude' =>  6.2333, 'longitude' =>  8.2833],
            ['state' => 'Ebonyi', 'lga' => 'Ishielu',       'latitude' =>  6.6000, 'longitude' =>  8.0833],
            ['state' => 'Ebonyi', 'lga' => 'Ivo',           'latitude' =>  5.9833, 'longitude' =>  7.9500],
            ['state' => 'Ebonyi', 'lga' => 'Izzi',          'latitude' =>  6.5333, 'longitude' =>  8.2333],
            ['state' => 'Ebonyi', 'lga' => 'Ohaozara',      'latitude' =>  5.9667, 'longitude' =>  8.0000],
            ['state' => 'Ebonyi', 'lga' => 'Ohaukwu',       'latitude' =>  6.7167, 'longitude' =>  8.0333],
            ['state' => 'Ebonyi', 'lga' => 'Onicha',        'latitude' =>  6.1167, 'longitude' =>  8.0000],

            // ----------------------------------------------------------------
            // EDO
            // ----------------------------------------------------------------
            ['state' => 'Edo', 'lga' => 'Akoko-Edo',       'latitude' =>  7.1333, 'longitude' =>  6.0667],
            ['state' => 'Edo', 'lga' => 'Egor',            'latitude' =>  6.3333, 'longitude' =>  5.6167],
            ['state' => 'Edo', 'lga' => 'Esan Central',    'latitude' =>  6.5000, 'longitude' =>  6.1000],
            ['state' => 'Edo', 'lga' => 'Esan North East', 'latitude' =>  6.6333, 'longitude' =>  6.2833],
            ['state' => 'Edo', 'lga' => 'Esan South East', 'latitude' =>  6.3833, 'longitude' =>  6.3167],
            ['state' => 'Edo', 'lga' => 'Esan West',       'latitude' =>  6.5500, 'longitude' =>  6.0333],
            ['state' => 'Edo', 'lga' => 'Etsako Central',  'latitude' =>  7.0500, 'longitude' =>  6.2500],
            ['state' => 'Edo', 'lga' => 'Etsako East',     'latitude' =>  7.1333, 'longitude' =>  6.4833],
            ['state' => 'Edo', 'lga' => 'Etsako West',     'latitude' =>  7.1333, 'longitude' =>  6.0500],
            ['state' => 'Edo', 'lga' => 'Igueben',         'latitude' =>  6.4833, 'longitude' =>  6.2333],
            ['state' => 'Edo', 'lga' => 'Ikpoba Okha',     'latitude' =>  6.2833, 'longitude' =>  5.6667],
            ['state' => 'Edo', 'lga' => 'Oredo',           'latitude' =>  6.3350, 'longitude' =>  5.6278],
            ['state' => 'Edo', 'lga' => 'Orhionmwon',      'latitude' =>  6.1000, 'longitude' =>  5.8500],
            ['state' => 'Edo', 'lga' => 'Ovia North East', 'latitude' =>  6.4333, 'longitude' =>  5.3667],
            ['state' => 'Edo', 'lga' => 'Ovia South West', 'latitude' =>  6.2333, 'longitude' =>  5.1833],
            ['state' => 'Edo', 'lga' => 'Owan East',       'latitude' =>  7.0000, 'longitude' =>  5.8167],
            ['state' => 'Edo', 'lga' => 'Owan West',       'latitude' =>  7.1167, 'longitude' =>  5.6833],
            ['state' => 'Edo', 'lga' => 'Uhunmwonde',      'latitude' =>  6.1667, 'longitude' =>  5.8833],

            // ----------------------------------------------------------------
            // EKITI
            // ----------------------------------------------------------------
            ['state' => 'Ekiti', 'lga' => 'Ado Ekiti',        'latitude' =>  7.6233, 'longitude' =>  5.2211],
            ['state' => 'Ekiti', 'lga' => 'Efon',             'latitude' =>  7.6667, 'longitude' =>  5.0667],
            ['state' => 'Ekiti', 'lga' => 'Ekiti East',       'latitude' =>  7.5000, 'longitude' =>  5.5667],
            ['state' => 'Ekiti', 'lga' => 'Ekiti South West', 'latitude' =>  7.4333, 'longitude' =>  5.1500],
            ['state' => 'Ekiti', 'lga' => 'Ekiti West',       'latitude' =>  7.8333, 'longitude' =>  5.0000],
            ['state' => 'Ekiti', 'lga' => 'Emure',            'latitude' =>  7.4333, 'longitude' =>  5.4667],
            ['state' => 'Ekiti', 'lga' => 'Gbonyin',          'latitude' =>  7.7167, 'longitude' =>  5.4667],
            ['state' => 'Ekiti', 'lga' => 'Ido Osi',          'latitude' =>  7.8500, 'longitude' =>  5.4167],
            ['state' => 'Ekiti', 'lga' => 'Ijero',            'latitude' =>  7.8167, 'longitude' =>  5.0667],
            ['state' => 'Ekiti', 'lga' => 'Ikere',            'latitude' =>  7.5000, 'longitude' =>  5.2333],
            ['state' => 'Ekiti', 'lga' => 'Ikole',            'latitude' =>  7.7667, 'longitude' =>  5.4833],
            ['state' => 'Ekiti', 'lga' => 'Ilejemeje',        'latitude' =>  7.9833, 'longitude' =>  5.4167],
            ['state' => 'Ekiti', 'lga' => 'Irepodun/Ifelodun','latitude' =>  7.6833, 'longitude' =>  5.0500],
            ['state' => 'Ekiti', 'lga' => 'Ise/Orun',         'latitude' =>  7.4667, 'longitude' =>  5.3833],
            ['state' => 'Ekiti', 'lga' => 'Moba',             'latitude' =>  7.9333, 'longitude' =>  5.4167],
            ['state' => 'Ekiti', 'lga' => 'Oye',              'latitude' =>  7.7833, 'longitude' =>  5.3667],

            // ----------------------------------------------------------------
            // ENUGU
            // ----------------------------------------------------------------
            ['state' => 'Enugu', 'lga' => 'Aninri',         'latitude' =>  6.1500, 'longitude' =>  7.4333],
            ['state' => 'Enugu', 'lga' => 'Awgu',           'latitude' =>  6.0667, 'longitude' =>  7.5667],
            ['state' => 'Enugu', 'lga' => 'Enugu East',     'latitude' =>  6.4500, 'longitude' =>  7.5667],
            ['state' => 'Enugu', 'lga' => 'Enugu North',    'latitude' =>  6.4698, 'longitude' =>  7.5361],
            ['state' => 'Enugu', 'lga' => 'Enugu South',    'latitude' =>  6.4282, 'longitude' =>  7.5008],
            ['state' => 'Enugu', 'lga' => 'Ezeagu',         'latitude' =>  6.2833, 'longitude' =>  7.4333],
            ['state' => 'Enugu', 'lga' => 'Igbo Etiti',     'latitude' =>  6.7500, 'longitude' =>  7.3833],
            ['state' => 'Enugu', 'lga' => 'Igbo Eze North', 'latitude' =>  6.9167, 'longitude' =>  7.5000],
            ['state' => 'Enugu', 'lga' => 'Igbo Eze South', 'latitude' =>  6.8000, 'longitude' =>  7.4833],
            ['state' => 'Enugu', 'lga' => 'Isi Uzo',        'latitude' =>  6.8667, 'longitude' =>  7.7500],
            ['state' => 'Enugu', 'lga' => 'Nkanu East',     'latitude' =>  6.2833, 'longitude' =>  7.6833],
            ['state' => 'Enugu', 'lga' => 'Nkanu West',     'latitude' =>  6.3333, 'longitude' =>  7.5833],
            ['state' => 'Enugu', 'lga' => 'Nsukka',         'latitude' =>  6.8574, 'longitude' =>  7.3954],
            ['state' => 'Enugu', 'lga' => 'Oji River',      'latitude' =>  6.3833, 'longitude' =>  7.2000],
            ['state' => 'Enugu', 'lga' => 'Udenu',          'latitude' =>  7.0333, 'longitude' =>  7.4167],
            ['state' => 'Enugu', 'lga' => 'Udi',            'latitude' =>  6.3167, 'longitude' =>  7.4500],
            ['state' => 'Enugu', 'lga' => 'Uzo Uwani',      'latitude' =>  6.6500, 'longitude' =>  7.1167],

            // ----------------------------------------------------------------
            // FCT
            // ----------------------------------------------------------------
            ['state' => 'FCT', 'lga' => 'Abaji',           'latitude' =>  8.4719, 'longitude' =>  6.9419],
            ['state' => 'FCT', 'lga' => 'Abuja Municipal', 'latitude' =>  8.8974, 'longitude' =>  7.1864],
            ['state' => 'FCT', 'lga' => 'Bwari',           'latitude' =>  9.0804, 'longitude' =>  7.3697],
            ['state' => 'FCT', 'lga' => 'Gwagwalada',      'latitude' =>  8.9438, 'longitude' =>  7.0806],
            ['state' => 'FCT', 'lga' => 'Kuje',            'latitude' =>  8.8806, 'longitude' =>  7.2294],
            ['state' => 'FCT', 'lga' => 'Kwali',           'latitude' =>  8.7428, 'longitude' =>  7.0153],

            // ----------------------------------------------------------------
            // GOMBE
            // ----------------------------------------------------------------
            ['state' => 'Gombe', 'lga' => 'Akko',          'latitude' => 10.3167, 'longitude' => 11.0667],
            ['state' => 'Gombe', 'lga' => 'Balanga',       'latitude' =>  9.9667, 'longitude' => 11.5667],
            ['state' => 'Gombe', 'lga' => 'Billiri',       'latitude' =>  9.8667, 'longitude' => 11.2167],
            ['state' => 'Gombe', 'lga' => 'Dukku',         'latitude' => 10.8167, 'longitude' => 11.0000],
            ['state' => 'Gombe', 'lga' => 'Funakaye',      'latitude' => 10.4333, 'longitude' => 11.7833],
            ['state' => 'Gombe', 'lga' => 'Gombe',         'latitude' => 10.2897, 'longitude' => 11.1673],
            ['state' => 'Gombe', 'lga' => 'Kaltungo',      'latitude' =>  9.8203, 'longitude' => 11.3181],
            ['state' => 'Gombe', 'lga' => 'Kwami',         'latitude' => 10.4500, 'longitude' => 11.4167],
            ['state' => 'Gombe', 'lga' => 'Nafada',        'latitude' => 11.1000, 'longitude' => 11.3333],
            ['state' => 'Gombe', 'lga' => 'Shongom',       'latitude' =>  9.9333, 'longitude' => 11.0833],
            ['state' => 'Gombe', 'lga' => 'Yamaltu/Deba',  'latitude' => 10.4667, 'longitude' => 11.2167],

            // ----------------------------------------------------------------
            // IMO
            // ----------------------------------------------------------------
            ['state' => 'Imo', 'lga' => 'Aboh Mbaise',     'latitude' =>  5.5000, 'longitude' =>  7.1833],
            ['state' => 'Imo', 'lga' => 'Ahiazu Mbaise',   'latitude' =>  5.5333, 'longitude' =>  7.1500],
            ['state' => 'Imo', 'lga' => 'Ehime Mbano',     'latitude' =>  5.6500, 'longitude' =>  7.2333],
            ['state' => 'Imo', 'lga' => 'Ezinihitte',      'latitude' =>  5.5833, 'longitude' =>  7.2167],
            ['state' => 'Imo', 'lga' => 'Ideato North',    'latitude' =>  5.8500, 'longitude' =>  7.2167],
            ['state' => 'Imo', 'lga' => 'Ideato South',    'latitude' =>  5.7833, 'longitude' =>  7.2333],
            ['state' => 'Imo', 'lga' => 'Ihitte/Uboma',    'latitude' =>  5.7167, 'longitude' =>  7.3333],
            ['state' => 'Imo', 'lga' => 'Ikeduru',         'latitude' =>  5.6333, 'longitude' =>  7.1167],
            ['state' => 'Imo', 'lga' => 'Isiala Mbano',    'latitude' =>  5.7000, 'longitude' =>  7.2667],
            ['state' => 'Imo', 'lga' => 'Isu',             'latitude' =>  5.8167, 'longitude' =>  7.0667],
            ['state' => 'Imo', 'lga' => 'Mbaitoli',        'latitude' =>  5.6667, 'longitude' =>  7.0000],
            ['state' => 'Imo', 'lga' => 'Ngor Okpala',     'latitude' =>  5.5833, 'longitude' =>  7.0333],
            ['state' => 'Imo', 'lga' => 'Njaba',           'latitude' =>  5.7833, 'longitude' =>  7.1167],
            ['state' => 'Imo', 'lga' => 'Nkwerre',         'latitude' =>  5.8000, 'longitude' =>  7.0167],
            ['state' => 'Imo', 'lga' => 'Nwangele',        'latitude' =>  5.8500, 'longitude' =>  7.1000],
            ['state' => 'Imo', 'lga' => 'Obowo',           'latitude' =>  5.6500, 'longitude' =>  7.3500],
            ['state' => 'Imo', 'lga' => 'Oguta',           'latitude' =>  5.7167, 'longitude' =>  6.7833],
            ['state' => 'Imo', 'lga' => 'Ohaji/Egbema',    'latitude' =>  5.4167, 'longitude' =>  6.7667],
            ['state' => 'Imo', 'lga' => 'Okigwe',          'latitude' =>  5.8500, 'longitude' =>  7.3500],
            ['state' => 'Imo', 'lga' => 'Onuimo',          'latitude' =>  5.8833, 'longitude' =>  7.2000],
            ['state' => 'Imo', 'lga' => 'Orlu',            'latitude' =>  5.7833, 'longitude' =>  7.0333],
            ['state' => 'Imo', 'lga' => 'Orsu',            'latitude' =>  5.8333, 'longitude' =>  6.9333],
            ['state' => 'Imo', 'lga' => 'Oru East',        'latitude' =>  5.7500, 'longitude' =>  7.0000],
            ['state' => 'Imo', 'lga' => 'Oru West',        'latitude' =>  5.7333, 'longitude' =>  6.9167],
            ['state' => 'Imo', 'lga' => 'Owerri Municipal','latitude' =>  5.4836, 'longitude' =>  7.0333],
            ['state' => 'Imo', 'lga' => 'Owerri North',    'latitude' =>  5.5500, 'longitude' =>  7.0167],
            ['state' => 'Imo', 'lga' => 'Owerri West',     'latitude' =>  5.4833, 'longitude' =>  6.9500],

            // ----------------------------------------------------------------
            // JIGAWA
            // ----------------------------------------------------------------
            ['state' => 'Jigawa', 'lga' => 'Auyo',             'latitude' => 12.5000, 'longitude' =>  9.8500],
            ['state' => 'Jigawa', 'lga' => 'Babura',           'latitude' => 12.8500, 'longitude' =>  9.3167],
            ['state' => 'Jigawa', 'lga' => 'Biriniwa',         'latitude' => 12.1333, 'longitude' =>  9.8667],
            ['state' => 'Jigawa', 'lga' => 'Birnin Kudu',      'latitude' => 11.4500, 'longitude' =>  9.4833],
            ['state' => 'Jigawa', 'lga' => 'Buji',             'latitude' => 11.7333, 'longitude' =>  9.8000],
            ['state' => 'Jigawa', 'lga' => 'Dutse',            'latitude' => 11.7667, 'longitude' =>  9.3500],
            ['state' => 'Jigawa', 'lga' => 'Gagarawa',         'latitude' => 12.4333, 'longitude' =>  9.4667],
            ['state' => 'Jigawa', 'lga' => 'Garki',            'latitude' => 12.6500, 'longitude' =>  9.6167],
            ['state' => 'Jigawa', 'lga' => 'Gumel',            'latitude' => 12.6333, 'longitude' =>  9.3833],
            ['state' => 'Jigawa', 'lga' => 'Guri',             'latitude' => 12.5833, 'longitude' =>  9.9500],
            ['state' => 'Jigawa', 'lga' => 'Gwaram',           'latitude' => 11.2667, 'longitude' =>  9.7833],
            ['state' => 'Jigawa', 'lga' => 'Gwiwa',            'latitude' => 12.4333, 'longitude' =>  8.9833],
            ['state' => 'Jigawa', 'lga' => 'Hadejia',          'latitude' => 12.4500, 'longitude' => 10.0500],
            ['state' => 'Jigawa', 'lga' => 'Jahun',            'latitude' => 12.0167, 'longitude' =>  9.4500],
            ['state' => 'Jigawa', 'lga' => 'Kafin Hausa',      'latitude' => 12.5500, 'longitude' =>  9.5333],
            ['state' => 'Jigawa', 'lga' => 'Kaugama',          'latitude' => 12.2000, 'longitude' => 10.0833],
            ['state' => 'Jigawa', 'lga' => 'Kazaure',          'latitude' => 12.6667, 'longitude' =>  8.9833],
            ['state' => 'Jigawa', 'lga' => 'Kiri Kasama',      'latitude' => 12.7833, 'longitude' =>  9.7000],
            ['state' => 'Jigawa', 'lga' => 'Kiyawa',           'latitude' => 11.7833, 'longitude' =>  9.7167],
            ['state' => 'Jigawa', 'lga' => 'Maigatari',        'latitude' => 13.0333, 'longitude' =>  9.6500],
            ['state' => 'Jigawa', 'lga' => 'Malam Madori',     'latitude' => 12.8833, 'longitude' => 10.3167],
            ['state' => 'Jigawa', 'lga' => 'Miga',             'latitude' => 12.1667, 'longitude' =>  9.5667],
            ['state' => 'Jigawa', 'lga' => 'Ringim',           'latitude' => 12.1500, 'longitude' =>  9.1500],
            ['state' => 'Jigawa', 'lga' => 'Roni',             'latitude' => 12.8333, 'longitude' =>  9.0667],
            ['state' => 'Jigawa', 'lga' => 'Sule Tankarkar',   'latitude' => 11.6000, 'longitude' =>  9.5667],
            ['state' => 'Jigawa', 'lga' => 'Taura',            'latitude' => 12.5167, 'longitude' =>  9.8000],
            ['state' => 'Jigawa', 'lga' => 'Yankwashi',        'latitude' => 11.9333, 'longitude' =>  9.0333],

            // ----------------------------------------------------------------
            // KADUNA
            // ----------------------------------------------------------------
            ['state' => 'Kaduna', 'lga' => 'Birnin Gwari',    'latitude' => 11.0000, 'longitude' =>  6.7500],
            ['state' => 'Kaduna', 'lga' => 'Chikun',          'latitude' => 10.4167, 'longitude' =>  7.3333],
            ['state' => 'Kaduna', 'lga' => 'Giwa',            'latitude' => 11.2167, 'longitude' =>  7.6500],
            ['state' => 'Kaduna', 'lga' => 'Igabi',           'latitude' => 10.6833, 'longitude' =>  7.5000],
            ['state' => 'Kaduna', 'lga' => 'Ikara',           'latitude' => 11.3167, 'longitude' =>  8.1667],
            ['state' => 'Kaduna', 'lga' => "Jaba",            'latitude' =>  9.7667, 'longitude' =>  8.0500],
            ['state' => 'Kaduna', 'lga' => "Jema'a",          'latitude' =>  9.9500, 'longitude' =>  8.3333],
            ['state' => 'Kaduna', 'lga' => 'Kachia',          'latitude' => 10.0000, 'longitude' =>  7.9500],
            ['state' => 'Kaduna', 'lga' => 'Kaduna North',    'latitude' => 10.5333, 'longitude' =>  7.4333],
            ['state' => 'Kaduna', 'lga' => 'Kaduna South',    'latitude' => 10.4833, 'longitude' =>  7.4500],
            ['state' => 'Kaduna', 'lga' => 'Kagarko',         'latitude' => 10.1667, 'longitude' =>  7.5667],
            ['state' => 'Kaduna', 'lga' => 'Kajuru',          'latitude' => 10.3333, 'longitude' =>  7.6833],
            ['state' => 'Kaduna', 'lga' => 'Kaura',           'latitude' =>  9.6000, 'longitude' =>  8.0500],
            ['state' => 'Kaduna', 'lga' => 'Kauru',           'latitude' => 10.7667, 'longitude' =>  8.2167],
            ['state' => 'Kaduna', 'lga' => 'Kubau',           'latitude' => 11.1333, 'longitude' =>  7.9333],
            ['state' => 'Kaduna', 'lga' => 'Kudan',           'latitude' => 11.2167, 'longitude' =>  7.8333],
            ['state' => 'Kaduna', 'lga' => 'Lere',            'latitude' => 10.8833, 'longitude' =>  8.5500],
            ['state' => 'Kaduna', 'lga' => 'Makarfi',         'latitude' => 11.3000, 'longitude' =>  7.8833],
            ['state' => 'Kaduna', 'lga' => 'Sabon Gari',      'latitude' => 11.1167, 'longitude' =>  7.6333],
            ['state' => 'Kaduna', 'lga' => 'Sanga',           'latitude' =>  9.6833, 'longitude' =>  8.4000],
            ['state' => 'Kaduna', 'lga' => 'Soba',            'latitude' => 11.1833, 'longitude' =>  8.0333],
            ['state' => 'Kaduna', 'lga' => 'Zangon Kataf',    'latitude' =>  9.8333, 'longitude' =>  8.1167],
            ['state' => 'Kaduna', 'lga' => 'Zaria',           'latitude' => 11.0833, 'longitude' =>  7.7000],

            // ----------------------------------------------------------------
            // KANO
            // ----------------------------------------------------------------
            ['state' => 'Kano', 'lga' => 'Ajingi',          'latitude' => 11.9667, 'longitude' =>  9.0500],
            ['state' => 'Kano', 'lga' => 'Albasu',          'latitude' => 11.6833, 'longitude' =>  9.2167],
            ['state' => 'Kano', 'lga' => 'Bagwai',          'latitude' => 12.2333, 'longitude' =>  8.4667],
            ['state' => 'Kano', 'lga' => 'Bebeji',          'latitude' => 11.6333, 'longitude' =>  8.7333],
            ['state' => 'Kano', 'lga' => 'Bichi',           'latitude' => 12.2333, 'longitude' =>  8.2167],
            ['state' => 'Kano', 'lga' => 'Bunkure',         'latitude' => 11.6667, 'longitude' =>  8.8167],
            ['state' => 'Kano', 'lga' => 'Dala',            'latitude' => 12.0622, 'longitude' =>  8.5508],
            ['state' => 'Kano', 'lga' => 'Dambatta',        'latitude' => 12.4833, 'longitude' =>  8.5333],
            ['state' => 'Kano', 'lga' => 'Dawakin Kudu',    'latitude' => 11.8500, 'longitude' =>  8.5667],
            ['state' => 'Kano', 'lga' => 'Dawakin Tofa',    'latitude' => 12.1000, 'longitude' =>  8.3500],
            ['state' => 'Kano', 'lga' => 'Doguwa',          'latitude' => 11.2833, 'longitude' =>  8.7833],
            ['state' => 'Kano', 'lga' => 'Fagge',           'latitude' => 12.0197, 'longitude' =>  8.5361],
            ['state' => 'Kano', 'lga' => 'Gabasawa', 'latitude' => 12.1667, 'longitude' => 8.8333],
            ['state' => 'Kano', 'lga' => 'Garko',           'latitude' => 11.6333, 'longitude' =>  8.9000],
            ['state' => 'Kano', 'lga' => 'Garun Mallam',    'latitude' => 11.7000, 'longitude' =>  8.8000],
            ['state' => 'Kano', 'lga' => 'Gaya',            'latitude' => 11.8833, 'longitude' =>  9.0167],
            ['state' => 'Kano', 'lga' => 'Gezawa',          'latitude' => 12.1333, 'longitude' =>  8.6833],
            ['state' => 'Kano', 'lga' => 'Gwale',           'latitude' => 11.9932, 'longitude' =>  8.5229],
            ['state' => 'Kano', 'lga' => 'Gwarzo',          'latitude' => 12.0000, 'longitude' =>  8.0500],
            ['state' => 'Kano', 'lga' => 'Kabo',            'latitude' => 12.1833, 'longitude' =>  8.3167],
            ['state' => 'Kano', 'lga' => 'Kano Municipal',  'latitude' => 12.0022, 'longitude' =>  8.5920],
            ['state' => 'Kano', 'lga' => 'Karaye',          'latitude' => 11.8833, 'longitude' =>  8.1000],
            ['state' => 'Kano', 'lga' => 'Kibiya',          'latitude' => 11.8333, 'longitude' =>  9.0000],
            ['state' => 'Kano', 'lga' => 'Kiru',            'latitude' => 11.6000, 'longitude' =>  8.4833],
            ['state' => 'Kano', 'lga' => 'Kumbotso',        'latitude' => 12.0833, 'longitude' =>  8.4833],
            ['state' => 'Kano', 'lga' => 'Kunchi',          'latitude' => 12.4833, 'longitude' =>  8.4167],
            ['state' => 'Kano', 'lga' => 'Kura',            'latitude' => 11.8500, 'longitude' =>  8.4333],
            ['state' => 'Kano', 'lga' => 'Madobi',          'latitude' => 12.0167, 'longitude' =>  8.2333],
            ['state' => 'Kano', 'lga' => 'Makoda',          'latitude' => 12.4333, 'longitude' =>  8.3500],
            ['state' => 'Kano', 'lga' => 'Minjibir',        'latitude' => 12.2500, 'longitude' =>  8.7000],
            ['state' => 'Kano', 'lga' => 'Nassarawa',       'latitude' => 11.9804, 'longitude' =>  8.5650],
            ['state' => 'Kano', 'lga' => 'Rano',            'latitude' => 11.5500, 'longitude' =>  8.9167],
            ['state' => 'Kano', 'lga' => 'Rimin Gado',      'latitude' => 12.4000, 'longitude' =>  8.8667],
            ['state' => 'Kano', 'lga' => 'Rogo',            'latitude' => 11.5333, 'longitude' =>  8.7667],
            ['state' => 'Kano', 'lga' => 'Shanono',         'latitude' => 12.1167, 'longitude' =>  8.1167],
            ['state' => 'Kano', 'lga' => 'Sumaila',         'latitude' => 11.4167, 'longitude' =>  9.0667],
            ['state' => 'Kano', 'lga' => 'Takai',           'latitude' => 11.6833, 'longitude' =>  9.0833],
            ['state' => 'Kano', 'lga' => 'Tarauni',         'latitude' => 12.0411, 'longitude' =>  8.5636],
            ['state' => 'Kano', 'lga' => 'Tofa',            'latitude' => 12.1000, 'longitude' =>  8.2833],
            ['state' => 'Kano', 'lga' => 'Tsanyawa',        'latitude' => 12.3333, 'longitude' =>  8.1500],
            ['state' => 'Kano', 'lga' => 'Tudun Wada',      'latitude' => 11.5167, 'longitude' =>  8.6167],
            ['state' => 'Kano', 'lga' => 'Ungogo',          'latitude' => 12.1000, 'longitude' =>  8.5333],
            ['state' => 'Kano', 'lga' => 'Warawa',          'latitude' => 11.9000, 'longitude' =>  8.8000],
            ['state' => 'Kano', 'lga' => 'Wudil',           'latitude' => 11.8000, 'longitude' =>  8.8500],

            // ----------------------------------------------------------------
            // KATSINA
            // ----------------------------------------------------------------
            ['state' => 'Katsina', 'lga' => 'Bakori',         'latitude' => 12.0167, 'longitude' =>  7.4333],
            ['state' => 'Katsina', 'lga' => 'Batagarawa',     'latitude' => 12.9333, 'longitude' =>  7.5167],
            ['state' => 'Katsina', 'lga' => 'Batsari',        'latitude' => 12.8500, 'longitude' =>  7.2833],
            ['state' => 'Katsina', 'lga' => 'Baure',          'latitude' => 12.8000, 'longitude' =>  9.0167],
            ['state' => 'Katsina', 'lga' => 'Bindawa',        'latitude' => 13.0333, 'longitude' =>  7.9667],
            ['state' => 'Katsina', 'lga' => 'Charanchi',      'latitude' => 13.1500, 'longitude' =>  7.5833],
            ['state' => 'Katsina', 'lga' => 'Dan Musa',       'latitude' => 13.3333, 'longitude' =>  7.6167],
            ['state' => 'Katsina', 'lga' => 'Dandume',        'latitude' => 12.4167, 'longitude' =>  7.3667],
            ['state' => 'Katsina', 'lga' => 'Danja',          'latitude' => 12.2000, 'longitude' =>  7.6500],
            ['state' => 'Katsina', 'lga' => 'Daura',          'latitude' => 13.0500, 'longitude' =>  8.3167],
            ['state' => 'Katsina', 'lga' => 'Dutsi',          'latitude' => 13.1500, 'longitude' =>  8.1000],
            ['state' => 'Katsina', 'lga' => 'Dutsin-Ma',      'latitude' => 12.4667, 'longitude' =>  7.5167],
            ['state' => 'Katsina', 'lga' => 'Faskari',        'latitude' => 12.3333, 'longitude' =>  7.2333],
            ['state' => 'Katsina', 'lga' => 'Funtua',         'latitude' => 11.5167, 'longitude' =>  7.3167],
            ['state' => 'Katsina', 'lga' => 'Ingawa',         'latitude' => 12.8000, 'longitude' =>  8.3667],
            ['state' => 'Katsina', 'lga' => 'Jibia',          'latitude' => 13.3333, 'longitude' =>  7.2000],
            ['state' => 'Katsina', 'lga' => 'Kafur',          'latitude' => 12.5833, 'longitude' =>  8.1000],
            ['state' => 'Katsina', 'lga' => 'Kaita',          'latitude' => 13.3333, 'longitude' =>  7.9167],
            ['state' => 'Katsina', 'lga' => 'Kankara',        'latitude' => 12.5167, 'longitude' =>  7.4167],
            ['state' => 'Katsina', 'lga' => 'Kankia',         'latitude' => 13.1333, 'longitude' =>  7.8333],
            ['state' => 'Katsina', 'lga' => 'Katsina',        'latitude' => 12.9889, 'longitude' =>  7.6006],
            ['state' => 'Katsina', 'lga' => 'Kurfi',          'latitude' => 12.7000, 'longitude' =>  8.0833],
            ['state' => 'Katsina', 'lga' => 'Kusada',         'latitude' => 12.7000, 'longitude' =>  8.1667],
            ['state' => 'Katsina', 'lga' => "Ma'azu",         'latitude' => 11.6333, 'longitude' =>  7.6333],
            ['state' => 'Katsina', 'lga' => 'Malumfashi',     'latitude' => 11.7833, 'longitude' =>  7.6167],
            ['state' => 'Katsina', 'lga' => 'Mani',           'latitude' => 13.0667, 'longitude' =>  8.9000],
            ['state' => 'Katsina', 'lga' => 'Mashi',          'latitude' => 13.0000, 'longitude' =>  8.7500],
            ['state' => 'Katsina', 'lga' => 'Matazu',         'latitude' => 12.9333, 'longitude' =>  7.2333],
            ['state' => 'Katsina', 'lga' => 'Musawa',         'latitude' => 12.8500, 'longitude' =>  7.8667],
            ['state' => 'Katsina', 'lga' => 'Rimi',           'latitude' => 12.1833, 'longitude' =>  7.9500],
            ['state' => 'Katsina', 'lga' => 'Sabuwa',         'latitude' => 12.0667, 'longitude' =>  7.2667],
            ['state' => 'Katsina', 'lga' => 'Safana',         'latitude' => 12.7667, 'longitude' =>  7.1500],
            ['state' => 'Katsina', 'lga' => 'Sandamu',        'latitude' => 12.7167, 'longitude' =>  8.4167],
            ['state' => 'Katsina', 'lga' => 'Zango',          'latitude' => 12.7167, 'longitude' =>  8.5167],

            // ----------------------------------------------------------------
            // KEBBI
            // ----------------------------------------------------------------
            ['state' => 'Kebbi', 'lga' => 'Aleiro',          'latitude' => 11.3167, 'longitude' =>  5.0833],
            ['state' => 'Kebbi', 'lga' => 'Arewa Dandi',     'latitude' => 11.8333, 'longitude' =>  3.9500],
            ['state' => 'Kebbi', 'lga' => 'Argungu',         'latitude' => 12.7333, 'longitude' =>  4.5167],
            ['state' => 'Kebbi', 'lga' => 'Augie',           'latitude' => 12.2667, 'longitude' =>  4.4667],
            ['state' => 'Kebbi', 'lga' => 'Bagudo',          'latitude' => 11.5167, 'longitude' =>  4.4000],
            ['state' => 'Kebbi', 'lga' => 'Birnin Kebbi',    'latitude' => 12.4500, 'longitude' =>  4.1833],
            ['state' => 'Kebbi', 'lga' => 'Bunza',           'latitude' => 12.0833, 'longitude' =>  4.0500],
            ['state' => 'Kebbi', 'lga' => 'Dandi',           'latitude' => 11.9167, 'longitude' =>  4.0167],
            ['state' => 'Kebbi', 'lga' => 'Fakai',           'latitude' => 11.1500, 'longitude' =>  4.3667],
            ['state' => 'Kebbi', 'lga' => 'Gwandu',          'latitude' => 12.4833, 'longitude' =>  4.6333],
            ['state' => 'Kebbi', 'lga' => 'Jega',            'latitude' => 12.2167, 'longitude' =>  4.3833],
            ['state' => 'Kebbi', 'lga' => 'Kalgo',           'latitude' => 12.5333, 'longitude' =>  4.5667],
            ['state' => 'Kebbi', 'lga' => 'Koko/Besse',      'latitude' => 11.4333, 'longitude' =>  4.5167],
            ['state' => 'Kebbi', 'lga' => 'Maiyama',         'latitude' => 11.3833, 'longitude' =>  4.5000],
            ['state' => 'Kebbi', 'lga' => 'Ngaski',          'latitude' => 11.0167, 'longitude' =>  4.2500],
            ['state' => 'Kebbi', 'lga' => 'Sakaba',          'latitude' => 11.7833, 'longitude' =>  5.6667],
            ['state' => 'Kebbi', 'lga' => 'Shanga',          'latitude' => 11.4000, 'longitude' =>  4.6000],
            ['state' => 'Kebbi', 'lga' => 'Suru',            'latitude' => 12.1167, 'longitude' =>  4.5667],
            ['state' => 'Kebbi', 'lga' => 'Wasagu/Danko',    'latitude' => 11.3500, 'longitude' =>  5.8333],
            ['state' => 'Kebbi', 'lga' => 'Yauri',           'latitude' => 11.8833, 'longitude' =>  4.9000],
            ['state' => 'Kebbi', 'lga' => 'Zuru',            'latitude' => 11.4333, 'longitude' =>  5.2333],

            // ----------------------------------------------------------------
            // KOGI
            // ----------------------------------------------------------------
            ['state' => 'Kogi', 'lga' => 'Adavi',           'latitude' =>  7.5500, 'longitude' =>  6.7167],
            ['state' => 'Kogi', 'lga' => 'Ajaokuta',        'latitude' =>  7.5667, 'longitude' =>  6.6500],
            ['state' => 'Kogi', 'lga' => 'Ankpa',           'latitude' =>  7.3833, 'longitude' =>  7.6167],
            ['state' => 'Kogi', 'lga' => 'Bassa',           'latitude' =>  8.1500, 'longitude' =>  6.7333],
            ['state' => 'Kogi', 'lga' => 'Dekina',          'latitude' =>  7.6833, 'longitude' =>  7.0833],
            ['state' => 'Kogi', 'lga' => 'Ibaji',           'latitude' =>  7.0000, 'longitude' =>  6.7333],
            ['state' => 'Kogi', 'lga' => 'Idah',            'latitude' =>  7.1000, 'longitude' =>  6.7333],
            ['state' => 'Kogi', 'lga' => 'Igalamela Odolu', 'latitude' =>  7.3167, 'longitude' =>  6.9833],
            ['state' => 'Kogi', 'lga' => 'Ijumu',           'latitude' =>  7.9500, 'longitude' =>  5.9500],
            ['state' => 'Kogi', 'lga' => 'Kabba/Bunu',      'latitude' =>  7.8167, 'longitude' =>  6.0667],
            ['state' => 'Kogi', 'lga' => 'Kogi',            'latitude' =>  7.7833, 'longitude' =>  6.7667],
            ['state' => 'Kogi', 'lga' => 'Lokoja',          'latitude' =>  7.8036, 'longitude' =>  6.7330],
            ['state' => 'Kogi', 'lga' => 'Mopa Muro',       'latitude' =>  8.0000, 'longitude' =>  5.8833],
            ['state' => 'Kogi', 'lga' => 'Ofu',             'latitude' =>  7.1833, 'longitude' =>  6.7500],
            ['state' => 'Kogi', 'lga' => 'Ogori/Mangongo',  'latitude' =>  7.7833, 'longitude' =>  6.2667],
            ['state' => 'Kogi', 'lga' => 'Okehi',           'latitude' =>  7.6167, 'longitude' =>  6.7500],
            ['state' => 'Kogi', 'lga' => 'Okene',           'latitude' =>  7.5500, 'longitude' =>  6.2333],
            ['state' => 'Kogi', 'lga' => 'Olamaboro',       'latitude' =>  7.1167, 'longitude' =>  7.4833],
            ['state' => 'Kogi', 'lga' => 'Omala',           'latitude' =>  7.8167, 'longitude' =>  7.3500],
            ['state' => 'Kogi', 'lga' => 'Yagba East',      'latitude' =>  8.1333, 'longitude' =>  5.8833],
            ['state' => 'Kogi', 'lga' => 'Yagba West',      'latitude' =>  8.1667, 'longitude' =>  5.7167],

            // ----------------------------------------------------------------
            // KWARA
            // ----------------------------------------------------------------
            ['state' => 'Kwara', 'lga' => 'Asa',            'latitude' =>  8.4167, 'longitude' =>  4.6833],
            ['state' => 'Kwara', 'lga' => 'Baruten',        'latitude' => 10.6333, 'longitude' =>  3.4667],
            ['state' => 'Kwara', 'lga' => 'Edu',            'latitude' =>  9.4167, 'longitude' =>  5.1000],
            ['state' => 'Kwara', 'lga' => 'Ekiti',          'latitude' =>  8.4500, 'longitude' =>  5.3000],
            ['state' => 'Kwara', 'lga' => 'Ifelodun',       'latitude' =>  8.1167, 'longitude' =>  5.0833],
            ['state' => 'Kwara', 'lga' => 'Ilorin East',    'latitude' =>  8.4667, 'longitude' =>  4.6667],
            ['state' => 'Kwara', 'lga' => 'Ilorin South',   'latitude' =>  8.4500, 'longitude' =>  4.5500],
            ['state' => 'Kwara', 'lga' => 'Ilorin West',    'latitude' =>  8.4966, 'longitude' =>  4.5421],
            ['state' => 'Kwara', 'lga' => 'Irepodun',       'latitude' =>  8.0167, 'longitude' =>  5.0000],
            ['state' => 'Kwara', 'lga' => 'Isin',           'latitude' =>  8.5500, 'longitude' =>  5.3833],
            ['state' => 'Kwara', 'lga' => 'Kaiama',         'latitude' =>  9.5833, 'longitude' =>  3.9500],
            ['state' => 'Kwara', 'lga' => 'Moro',           'latitude' =>  8.7667, 'longitude' =>  4.7667],
            ['state' => 'Kwara', 'lga' => 'Offa',           'latitude' =>  8.1500, 'longitude' =>  4.7167],
            ['state' => 'Kwara', 'lga' => 'Oke Ero',        'latitude' =>  8.2333, 'longitude' =>  5.3667],
            ['state' => 'Kwara', 'lga' => 'Oyun',           'latitude' =>  8.1500, 'longitude' =>  4.8167],
            ['state' => 'Kwara', 'lga' => 'Pategi',         'latitude' =>  8.7333, 'longitude' =>  5.7500],

            // ----------------------------------------------------------------
            // LAGOS
            // ----------------------------------------------------------------
            ['state' => 'Lagos', 'lga' => 'Agege',              'latitude' =>  6.6208, 'longitude' =>  3.3228],
            ['state' => 'Lagos', 'lga' => 'Ajeromi-Ifelodun',   'latitude' =>  6.4683, 'longitude' =>  3.3267],
            ['state' => 'Lagos', 'lga' => 'Alimosho',           'latitude' =>  6.6096, 'longitude' =>  3.2692],
            ['state' => 'Lagos', 'lga' => 'Amuwo-Odofin',       'latitude' =>  6.4700, 'longitude' =>  3.3100],
            ['state' => 'Lagos', 'lga' => 'Apapa',              'latitude' =>  6.4490, 'longitude' =>  3.3600],
            ['state' => 'Lagos', 'lga' => 'Badagry',            'latitude' =>  6.4143, 'longitude' =>  2.8879],
            ['state' => 'Lagos', 'lga' => 'Epe',                'latitude' =>  6.5924, 'longitude' =>  3.9792],
            ['state' => 'Lagos', 'lga' => 'Eti-Osa',            'latitude' =>  6.4351, 'longitude' =>  3.4513],
            ['state' => 'Lagos', 'lga' => 'Ibeju-Lekki',        'latitude' =>  6.4333, 'longitude' =>  3.8667],
            ['state' => 'Lagos', 'lga' => 'Ifako-Ijaiye',       'latitude' =>  6.6500, 'longitude' =>  3.2833],
            ['state' => 'Lagos', 'lga' => 'Ikeja',              'latitude' =>  6.5954, 'longitude' =>  3.3378],
            ['state' => 'Lagos', 'lga' => 'Ikorodu',            'latitude' =>  6.6194, 'longitude' =>  3.5064],
            ['state' => 'Lagos', 'lga' => 'Kosofe',             'latitude' =>  6.5833, 'longitude' =>  3.4000],
            ['state' => 'Lagos', 'lga' => 'Lagos Island',       'latitude' =>  6.4543, 'longitude' =>  3.3940],
            ['state' => 'Lagos', 'lga' => 'Lagos Mainland',     'latitude' =>  6.4969, 'longitude' =>  3.3720],
            ['state' => 'Lagos', 'lga' => 'Mushin',             'latitude' =>  6.5298, 'longitude' =>  3.3544],
            ['state' => 'Lagos', 'lga' => 'Ojo',                'latitude' =>  6.4667, 'longitude' =>  3.2167],
            ['state' => 'Lagos', 'lga' => 'Oshodi-Isolo',       'latitude' =>  6.5477, 'longitude' =>  3.3392],
            ['state' => 'Lagos', 'lga' => 'Shomolu',            'latitude' =>  6.5455, 'longitude' =>  3.3797],
            ['state' => 'Lagos', 'lga' => 'Surulere',           'latitude' =>  6.5059, 'longitude' =>  3.3565],

            // ----------------------------------------------------------------
            // NASARAWA
            // ----------------------------------------------------------------
            ['state' => 'Nasarawa', 'lga' => 'Akwanga',      'latitude' =>  8.9167, 'longitude' =>  8.4000],
            ['state' => 'Nasarawa', 'lga' => 'Awe',          'latitude' =>  8.3167, 'longitude' =>  8.7167],
            ['state' => 'Nasarawa', 'lga' => 'Doma',         'latitude' =>  8.3500, 'longitude' =>  8.3167],
            ['state' => 'Nasarawa', 'lga' => 'Karu',         'latitude' =>  8.7167, 'longitude' =>  7.4500],
            ['state' => 'Nasarawa', 'lga' => 'Keana',        'latitude' =>  8.0833, 'longitude' =>  8.6833],
            ['state' => 'Nasarawa', 'lga' => 'Keffi',        'latitude' =>  8.8500, 'longitude' =>  7.8667],
            ['state' => 'Nasarawa', 'lga' => 'Kokona',       'latitude' =>  9.1500, 'longitude' =>  7.9167],
            ['state' => 'Nasarawa', 'lga' => 'Lafia',        'latitude' =>  8.4860, 'longitude' =>  8.5210],
            ['state' => 'Nasarawa', 'lga' => 'Nasarawa',     'latitude' =>  8.5500, 'longitude' =>  7.7000],
            ['state' => 'Nasarawa', 'lga' => 'Nasarawa Egon','latitude' =>  8.6667, 'longitude' =>  8.4500],
            ['state' => 'Nasarawa', 'lga' => 'Obi',          'latitude' =>  8.4833, 'longitude' =>  8.8833],
            ['state' => 'Nasarawa', 'lga' => 'Toto',         'latitude' =>  8.5667, 'longitude' =>  7.5167],
            ['state' => 'Nasarawa', 'lga' => 'Wamba',        'latitude' =>  8.9333, 'longitude' =>  8.5833],

            // ----------------------------------------------------------------
            // NIGER
            // ----------------------------------------------------------------
            ['state' => 'Niger', 'lga' => 'Agaie',           'latitude' =>  9.0000, 'longitude' =>  6.2000],
            ['state' => 'Niger', 'lga' => 'Agwara',          'latitude' => 10.3333, 'longitude' =>  5.2333],
            ['state' => 'Niger', 'lga' => 'Bida',            'latitude' =>  9.0833, 'longitude' =>  6.0167],
            ['state' => 'Niger', 'lga' => 'Borgu',           'latitude' => 10.7333, 'longitude' =>  4.0500],
            ['state' => 'Niger', 'lga' => 'Bosso',           'latitude' =>  9.6833, 'longitude' =>  6.5333],
            ['state' => 'Niger', 'lga' => 'Chanchaga',       'latitude' =>  9.6167, 'longitude' =>  6.5500],
            ['state' => 'Niger', 'lga' => 'Edati',           'latitude' =>  9.8833, 'longitude' =>  6.1500],
            ['state' => 'Niger', 'lga' => 'Gbako',           'latitude' =>  9.2833, 'longitude' =>  6.1167],
            ['state' => 'Niger', 'lga' => 'Gurara',          'latitude' =>  9.6500, 'longitude' =>  7.0333],
            ['state' => 'Niger', 'lga' => 'Katcha',          'latitude' =>  9.0833, 'longitude' =>  6.3167],
            ['state' => 'Niger', 'lga' => 'Kontagora',       'latitude' => 10.4000, 'longitude' =>  5.4667],
            ['state' => 'Niger', 'lga' => 'Lapai',           'latitude' =>  9.0333, 'longitude' =>  6.5833],
            ['state' => 'Niger', 'lga' => 'Lavun',           'latitude' =>  9.1833, 'longitude' =>  5.9000],
            ['state' => 'Niger', 'lga' => 'Magama',          'latitude' => 10.1167, 'longitude' =>  5.8333],
            ['state' => 'Niger', 'lga' => 'Mariga',          'latitude' => 10.5167, 'longitude' =>  5.9167],
            ['state' => 'Niger', 'lga' => 'Mashegu',         'latitude' => 10.4667, 'longitude' =>  5.1333],
            ['state' => 'Niger', 'lga' => 'Mokwa',           'latitude' =>  9.2500, 'longitude' =>  5.0500],
            ['state' => 'Niger', 'lga' => 'Munya',           'latitude' => 10.4167, 'longitude' =>  6.7167],
            ['state' => 'Niger', 'lga' => 'Paikoro',         'latitude' =>  9.9167, 'longitude' =>  6.7833],
            ['state' => 'Niger', 'lga' => 'Rafi',            'latitude' => 10.4667, 'longitude' =>  6.2167],
            ['state' => 'Niger', 'lga' => 'Rijau',           'latitude' => 11.0833, 'longitude' =>  5.2500],
            ['state' => 'Niger', 'lga' => 'Shiroro',         'latitude' =>  9.9833, 'longitude' =>  6.8667],
            ['state' => 'Niger', 'lga' => 'Suleja',          'latitude' =>  9.1833, 'longitude' =>  7.1833],
            ['state' => 'Niger', 'lga' => 'Tafa',            'latitude' =>  9.4500, 'longitude' =>  7.2000],
            ['state' => 'Niger', 'lga' => 'Wushishi',        'latitude' =>  9.9167, 'longitude' =>  6.0500],

            // ----------------------------------------------------------------
            // OGUN
            // ----------------------------------------------------------------
            ['state' => 'Ogun', 'lga' => 'Abeokuta North',  'latitude' =>  7.1833, 'longitude' =>  3.3500],
            ['state' => 'Ogun', 'lga' => 'Abeokuta South',  'latitude' =>  7.1456, 'longitude' =>  3.3522],
            ['state' => 'Ogun', 'lga' => 'Ado-Odo/Ota',     'latitude' =>  6.7000, 'longitude' =>  3.1667],
            ['state' => 'Ogun', 'lga' => 'Egbado North',    'latitude' =>  8.0000, 'longitude' =>  2.8833],
            ['state' => 'Ogun', 'lga' => 'Egbado South',    'latitude' =>  7.1333, 'longitude' =>  2.8667],
            ['state' => 'Ogun', 'lga' => 'Ewekoro',         'latitude' =>  6.9833, 'longitude' =>  3.2333],
            ['state' => 'Ogun', 'lga' => 'Ifo',             'latitude' =>  6.8167, 'longitude' =>  3.2167],
            ['state' => 'Ogun', 'lga' => 'Ijebu East',      'latitude' =>  6.8333, 'longitude' =>  4.0333],
            ['state' => 'Ogun', 'lga' => 'Ijebu North',     'latitude' =>  6.9333, 'longitude' =>  3.9833],
            ['state' => 'Ogun', 'lga' => 'Ijebu North East','latitude' =>  6.9833, 'longitude' =>  4.1167],
            ['state' => 'Ogun', 'lga' => 'Ijebu Ode',       'latitude' =>  6.8167, 'longitude' =>  3.9333],
            ['state' => 'Ogun', 'lga' => 'Ikenne',          'latitude' =>  6.8667, 'longitude' =>  3.6833],
            ['state' => 'Ogun', 'lga' => 'Imeko-Afon',      'latitude' =>  7.7167, 'longitude' =>  3.0000],
            ['state' => 'Ogun', 'lga' => 'Ipokia',          'latitude' =>  6.5833, 'longitude' =>  2.8500],
            ['state' => 'Ogun', 'lga' => 'Obafemi-Owode',   'latitude' =>  7.0333, 'longitude' =>  3.4833],
            ['state' => 'Ogun', 'lga' => 'Odeda',           'latitude' =>  7.2167, 'longitude' =>  3.3167],
            ['state' => 'Ogun', 'lga' => 'Odogbolu',        'latitude' =>  6.9000, 'longitude' =>  3.8333],
            ['state' => 'Ogun', 'lga' => 'Ogun Waterside',  'latitude' =>  6.6000, 'longitude' =>  4.1167],
            ['state' => 'Ogun', 'lga' => 'Remo North',      'latitude' =>  6.9833, 'longitude' =>  3.7500],
            ['state' => 'Ogun', 'lga' => 'Sagamu',          'latitude' =>  6.8404, 'longitude' =>  3.6374],

            // ----------------------------------------------------------------
            // ONDO
            // ----------------------------------------------------------------
            ['state' => 'Ondo', 'lga' => 'Akoko North East', 'latitude' =>  7.3833, 'longitude' =>  5.8833],
            ['state' => 'Ondo', 'lga' => 'Akoko North West', 'latitude' =>  7.4500, 'longitude' =>  5.7333],
            ['state' => 'Ondo', 'lga' => 'Akoko South East', 'latitude' =>  7.2000, 'longitude' =>  5.7833],
            ['state' => 'Ondo', 'lga' => 'Akoko South West', 'latitude' =>  7.2667, 'longitude' =>  5.6667],
            ['state' => 'Ondo', 'lga' => 'Akure North',      'latitude' =>  7.3167, 'longitude' =>  5.1500],
            ['state' => 'Ondo', 'lga' => 'Akure South',      'latitude' =>  7.2526, 'longitude' =>  5.1930],
            ['state' => 'Ondo', 'lga' => 'Ese Odo',          'latitude' =>  6.1167, 'longitude' =>  5.7333],
            ['state' => 'Ondo', 'lga' => 'Idanre',           'latitude' =>  7.1000, 'longitude' =>  5.1167],
            ['state' => 'Ondo', 'lga' => 'Ifedore',          'latitude' =>  7.1167, 'longitude' =>  5.2000],
            ['state' => 'Ondo', 'lga' => 'Ilaje',            'latitude' =>  6.0167, 'longitude' =>  5.3167],
            ['state' => 'Ondo', 'lga' => 'Ile Oluji/Okeigbo','latitude' =>  7.0000, 'longitude' =>  4.9667],
            ['state' => 'Ondo', 'lga' => 'Irele',            'latitude' =>  6.6333, 'longitude' =>  4.9333],
            ['state' => 'Ondo', 'lga' => 'Odigbo',           'latitude' =>  6.9167, 'longitude' =>  4.8167],
            ['state' => 'Ondo', 'lga' => 'Okitipupa',        'latitude' =>  6.5167, 'longitude' =>  4.7833],
            ['state' => 'Ondo', 'lga' => 'Ondo East',        'latitude' =>  7.1000, 'longitude' =>  4.8500],
            ['state' => 'Ondo', 'lga' => 'Ondo West',        'latitude' =>  7.0978, 'longitude' =>  4.8378],
            ['state' => 'Ondo', 'lga' => 'Ose',              'latitude' =>  7.3333, 'longitude' =>  5.4667],
            ['state' => 'Ondo', 'lga' => 'Owo',              'latitude' =>  7.1978, 'longitude' =>  5.5889],

            // ----------------------------------------------------------------
            // OSUN
            // ----------------------------------------------------------------
            ['state' => 'Osun', 'lga' => 'Atakumosa East',   'latitude' =>  7.5500, 'longitude' =>  4.9667],
            ['state' => 'Osun', 'lga' => 'Atakumosa West',   'latitude' =>  7.5000, 'longitude' =>  4.8833],
            ['state' => 'Osun', 'lga' => 'Ayedaade',         'latitude' =>  7.3333, 'longitude' =>  4.3833],
            ['state' => 'Osun', 'lga' => 'Ayedire',          'latitude' =>  7.4167, 'longitude' =>  4.3167],
            ['state' => 'Osun', 'lga' => 'Boluwaduro',       'latitude' =>  7.7167, 'longitude' =>  4.8333],
            ['state' => 'Osun', 'lga' => 'Boripe',           'latitude' =>  7.6667, 'longitude' =>  4.6333],
            ['state' => 'Osun', 'lga' => 'Ede North',        'latitude' =>  7.7500, 'longitude' =>  4.4333],
            ['state' => 'Osun', 'lga' => 'Ede South',        'latitude' =>  7.7333, 'longitude' =>  4.4167],
            ['state' => 'Osun', 'lga' => 'Egbedore',         'latitude' =>  7.7833, 'longitude' =>  4.3333],
            ['state' => 'Osun', 'lga' => 'Ejigbo',           'latitude' =>  7.8833, 'longitude' =>  4.3167],
            ['state' => 'Osun', 'lga' => 'Ife Central',      'latitude' =>  7.4833, 'longitude' =>  4.5500],
            ['state' => 'Osun', 'lga' => 'Ife East',         'latitude' =>  7.5167, 'longitude' =>  4.6000],
            ['state' => 'Osun', 'lga' => 'Ife North',        'latitude' =>  7.5833, 'longitude' =>  4.5000],
            ['state' => 'Osun', 'lga' => 'Ife South',        'latitude' =>  7.4167, 'longitude' =>  4.5333],
            ['state' => 'Osun', 'lga' => 'Ifedayo',          'latitude' =>  7.8333, 'longitude' =>  4.9333],
            ['state' => 'Osun', 'lga' => 'Ifelodun',         'latitude' =>  7.8500, 'longitude' =>  4.5167],
            ['state' => 'Osun', 'lga' => 'Ila',              'latitude' =>  8.0167, 'longitude' =>  4.8833],
            ['state' => 'Osun', 'lga' => 'Ilesa East',       'latitude' =>  7.6333, 'longitude' =>  4.7500],
            ['state' => 'Osun', 'lga' => 'Ilesa West',       'latitude' =>  7.6167, 'longitude' =>  4.7333],
            ['state' => 'Osun', 'lga' => 'Irepodun',         'latitude' =>  7.8667, 'longitude' =>  4.6000],
            ['state' => 'Osun', 'lga' => 'Irewole',          'latitude' =>  7.3667, 'longitude' =>  4.3333],
            ['state' => 'Osun', 'lga' => 'Isokan',           'latitude' =>  7.3167, 'longitude' =>  4.4333],
            ['state' => 'Osun', 'lga' => 'Iwo',              'latitude' =>  7.6333, 'longitude' =>  4.1833],
            ['state' => 'Osun', 'lga' => 'Obokun',           'latitude' =>  7.7000, 'longitude' =>  4.8833],
            ['state' => 'Osun', 'lga' => 'Odo Otin',         'latitude' =>  7.9167, 'longitude' =>  4.6667],
            ['state' => 'Osun', 'lga' => 'Ola Oluwa',        'latitude' =>  7.3667, 'longitude' =>  4.2667],
            ['state' => 'Osun', 'lga' => 'Olorunda',         'latitude' =>  7.5333, 'longitude' =>  4.5167],
            ['state' => 'Osun', 'lga' => 'Oriade',           'latitude' =>  7.5000, 'longitude' =>  4.8167],
            ['state' => 'Osun', 'lga' => 'Orolu',            'latitude' =>  7.6167, 'longitude' =>  4.4500],
            ['state' => 'Osun', 'lga' => 'Osogbo',           'latitude' =>  7.7667, 'longitude' =>  4.5500],

            // ----------------------------------------------------------------
            // OYO
            // ----------------------------------------------------------------
            ['state' => 'Oyo', 'lga' => 'Afijio',            'latitude' =>  8.1333, 'longitude' =>  3.8667],
            ['state' => 'Oyo', 'lga' => 'Akinyele',          'latitude' =>  7.5000, 'longitude' =>  3.9167],
            ['state' => 'Oyo', 'lga' => 'Atiba',             'latitude' =>  7.8500, 'longitude' =>  3.9333],
            ['state' => 'Oyo', 'lga' => 'Atisbo',            'latitude' =>  8.5000, 'longitude' =>  3.2500],
            ['state' => 'Oyo', 'lga' => 'Egbeda',            'latitude' =>  7.4297, 'longitude' =>  3.8906],
            ['state' => 'Oyo', 'lga' => 'Ibadan North',      'latitude' =>  7.3964, 'longitude' =>  3.9167],
            ['state' => 'Oyo', 'lga' => 'Ibadan North East', 'latitude' =>  7.4000, 'longitude' =>  3.9500],
            ['state' => 'Oyo', 'lga' => 'Ibadan North West', 'latitude' =>  7.4167, 'longitude' =>  3.8833],
            ['state' => 'Oyo', 'lga' => 'Ibadan South East', 'latitude' =>  7.3500, 'longitude' =>  3.9333],
            ['state' => 'Oyo', 'lga' => 'Ibadan South West', 'latitude' =>  7.3667, 'longitude' =>  3.8833],
            ['state' => 'Oyo', 'lga' => 'Ibarapa Central',   'latitude' =>  7.5333, 'longitude' =>  3.0833],
            ['state' => 'Oyo', 'lga' => 'Ibarapa East',      'latitude' =>  7.5167, 'longitude' =>  3.3000],
            ['state' => 'Oyo', 'lga' => 'Ibarapa North',     'latitude' =>  7.6833, 'longitude' =>  3.0333],
            ['state' => 'Oyo', 'lga' => 'Ido',               'latitude' =>  7.3667, 'longitude' =>  3.8333],
            ['state' => 'Oyo', 'lga' => 'Irepo',             'latitude' =>  8.5500, 'longitude' =>  3.7667],
            ['state' => 'Oyo', 'lga' => 'Iseyin',            'latitude' =>  7.9667, 'longitude' =>  3.5333],
            ['state' => 'Oyo', 'lga' => 'Itesiwaju',         'latitude' =>  8.1667, 'longitude' =>  3.2667],
            ['state' => 'Oyo', 'lga' => 'Iwajowa',           'latitude' =>  8.4167, 'longitude' =>  3.3833],
            ['state' => 'Oyo', 'lga' => 'Kajola',            'latitude' =>  8.2500, 'longitude' =>  3.4833],
            ['state' => 'Oyo', 'lga' => 'Lagelu',            'latitude' =>  7.5167, 'longitude' =>  3.9833],
            ['state' => 'Oyo', 'lga' => 'Ogbomoso North',    'latitude' =>  8.1500, 'longitude' =>  4.2500],
            ['state' => 'Oyo', 'lga' => 'Ogbomoso South',    'latitude' =>  8.1167, 'longitude' =>  4.2333],
            ['state' => 'Oyo', 'lga' => 'Ogo Oluwa',         'latitude' =>  8.0667, 'longitude' =>  4.5167],
            ['state' => 'Oyo', 'lga' => 'Olorunsogo',        'latitude' =>  8.3167, 'longitude' =>  3.7833],
            ['state' => 'Oyo', 'lga' => 'Oluyole',           'latitude' =>  7.3167, 'longitude' =>  3.8667],
            ['state' => 'Oyo', 'lga' => 'Ona Ara',           'latitude' =>  7.3000, 'longitude' =>  4.0167],
            ['state' => 'Oyo', 'lga' => 'Orelope',           'latitude' =>  8.5500, 'longitude' =>  3.8833],
            ['state' => 'Oyo', 'lga' => 'Ori Ire',           'latitude' =>  8.2167, 'longitude' =>  4.4667],
            ['state' => 'Oyo', 'lga' => 'Oyo East',          'latitude' =>  7.8833, 'longitude' =>  3.9500],
            ['state' => 'Oyo', 'lga' => 'Oyo West',          'latitude' =>  7.8500, 'longitude' =>  3.9333],
            ['state' => 'Oyo', 'lga' => 'Saki East',         'latitude' =>  8.6000, 'longitude' =>  3.5333],
            ['state' => 'Oyo', 'lga' => 'Saki West',         'latitude' =>  8.6667, 'longitude' =>  3.3833],
            ['state' => 'Oyo', 'lga' => 'Surulere',          'latitude' =>  8.0500, 'longitude' =>  4.5833],

            // ----------------------------------------------------------------
            // PLATEAU
            // ----------------------------------------------------------------
            ['state' => 'Plateau', 'lga' => 'Barkin Ladi',   'latitude' =>  9.5333, 'longitude' =>  8.9000],
            ['state' => 'Plateau', 'lga' => 'Bassa',         'latitude' =>  9.9833, 'longitude' =>  8.8667],
            ['state' => 'Plateau', 'lga' => 'Bokkos',        'latitude' =>  9.3167, 'longitude' =>  9.0333],
            ['state' => 'Plateau', 'lga' => 'Jos East',      'latitude' =>  9.8667, 'longitude' =>  8.9500],
            ['state' => 'Plateau', 'lga' => 'Jos North',     'latitude' =>  9.9167, 'longitude' =>  8.8833],
            ['state' => 'Plateau', 'lga' => 'Jos South',     'latitude' =>  9.8167, 'longitude' =>  8.9167],
            ['state' => 'Plateau', 'lga' => 'Kanam',         'latitude' =>  9.5500, 'longitude' =>  9.5833],
            ['state' => 'Plateau', 'lga' => 'Kanke',         'latitude' =>  9.7667, 'longitude' =>  9.4667],
            ['state' => 'Plateau', 'lga' => 'Langtang North','latitude' =>  8.9333, 'longitude' =>  9.8000],
            ['state' => 'Plateau', 'lga' => 'Langtang South','latitude' =>  8.7667, 'longitude' =>  9.8167],
            ['state' => 'Plateau', 'lga' => 'Mangu',         'latitude' =>  9.4167, 'longitude' =>  9.0833],
            ['state' => 'Plateau', 'lga' => 'Mikang',        'latitude' =>  8.7333, 'longitude' =>  9.4667],
            ['state' => 'Plateau', 'lga' => 'Pankshin',      'latitude' =>  9.3333, 'longitude' =>  9.4333],
            ['state' => 'Plateau', 'lga' => "Qua'an Pan",    'latitude' =>  9.0167, 'longitude' =>  9.5000],
            ['state' => 'Plateau', 'lga' => 'Riyom',         'latitude' =>  9.6333, 'longitude' =>  8.7833],
            ['state' => 'Plateau', 'lga' => 'Shendam',       'latitude' =>  8.8833, 'longitude' =>  9.5333],
            ['state' => 'Plateau', 'lga' => 'Wase',          'latitude' =>  9.0667, 'longitude' =>  9.9667],

            // ----------------------------------------------------------------
            // RIVERS
            // ----------------------------------------------------------------
            ['state' => 'Rivers', 'lga' => 'Abua/Odual',     'latitude' =>  4.9167, 'longitude' =>  6.6500],
            ['state' => 'Rivers', 'lga' => 'Ahoada East',    'latitude' =>  5.1167, 'longitude' =>  6.6500],
            ['state' => 'Rivers', 'lga' => 'Ahoada West',    'latitude' =>  5.0833, 'longitude' =>  6.5500],
            ['state' => 'Rivers', 'lga' => 'Akuku-Toru',     'latitude' =>  4.7500, 'longitude' =>  6.9000],
            ['state' => 'Rivers', 'lga' => 'Andoni',         'latitude' =>  4.5500, 'longitude' =>  7.4167],
            ['state' => 'Rivers', 'lga' => 'Asari-Toru',     'latitude' =>  4.7667, 'longitude' =>  6.8500],
            ['state' => 'Rivers', 'lga' => 'Bonny',          'latitude' =>  4.4500, 'longitude' =>  7.1667],
            ['state' => 'Rivers', 'lga' => 'Degema',         'latitude' =>  4.7500, 'longitude' =>  6.7667],
            ['state' => 'Rivers', 'lga' => 'Eleme',          'latitude' =>  4.7906, 'longitude' =>  7.1433],
            ['state' => 'Rivers', 'lga' => 'Emohua',         'latitude' =>  4.9333, 'longitude' =>  6.9667],
            ['state' => 'Rivers', 'lga' => 'Etche',          'latitude' =>  5.1667, 'longitude' =>  7.0833],
            ['state' => 'Rivers', 'lga' => 'Gokana',         'latitude' =>  4.6794, 'longitude' =>  7.3667],
            ['state' => 'Rivers', 'lga' => 'Ikwerre',        'latitude' =>  5.0500, 'longitude' =>  7.0000],
            ['state' => 'Rivers', 'lga' => 'Khana',          'latitude' =>  4.4667, 'longitude' =>  7.4500],
            ['state' => 'Rivers', 'lga' => 'Obio/Akpor',     'latitude' =>  4.8590, 'longitude' =>  7.0174],
            ['state' => 'Rivers', 'lga' => 'Ogba/Egbema/Ndoni','latitude' => 5.3500,'longitude' =>  6.6500],
            ['state' => 'Rivers', 'lga' => 'Ogu/Bolo',       'latitude' =>  4.7000, 'longitude' =>  7.0833],
            ['state' => 'Rivers', 'lga' => 'Okrika',         'latitude' =>  4.7333, 'longitude' =>  7.0833],
            ['state' => 'Rivers', 'lga' => 'Omuma',          'latitude' =>  5.3333, 'longitude' =>  7.0000],
            ['state' => 'Rivers', 'lga' => 'Opobo/Nkoro',    'latitude' =>  4.5333, 'longitude' =>  7.4833],
            ['state' => 'Rivers', 'lga' => 'Oyigbo',         'latitude' =>  4.8333, 'longitude' =>  7.1667],
            ['state' => 'Rivers', 'lga' => 'Port Harcourt',  'latitude' =>  4.8156, 'longitude' =>  7.0498],
            ['state' => 'Rivers', 'lga' => 'Tai',            'latitude' =>  4.7000, 'longitude' =>  7.2167],

            // ----------------------------------------------------------------
            // SOKOTO
            // ----------------------------------------------------------------
            ['state' => 'Sokoto', 'lga' => 'Binji',          'latitude' => 13.2167, 'longitude' =>  5.0167],
            ['state' => 'Sokoto', 'lga' => 'Bodinga',        'latitude' => 12.9667, 'longitude' =>  5.1333],
            ['state' => 'Sokoto', 'lga' => 'Dange Shuni',    'latitude' => 13.0000, 'longitude' =>  5.2833],
            ['state' => 'Sokoto', 'lga' => 'Gada',           'latitude' => 13.6500, 'longitude' =>  5.5167],
            ['state' => 'Sokoto', 'lga' => 'Goronyo',        'latitude' => 13.3833, 'longitude' =>  5.6500],
            ['state' => 'Sokoto', 'lga' => 'Gudu',           'latitude' => 13.8000, 'longitude' =>  5.2833],
            ['state' => 'Sokoto', 'lga' => 'Gwadabawa',      'latitude' => 13.3667, 'longitude' =>  5.2333],
            ['state' => 'Sokoto', 'lga' => 'Illela',         'latitude' => 13.7167, 'longitude' =>  5.2833],
            ['state' => 'Sokoto', 'lga' => 'Isa',            'latitude' => 13.1833, 'longitude' =>  6.4000],
            ['state' => 'Sokoto', 'lga' => 'Kebbe',          'latitude' => 12.2667, 'longitude' =>  4.7167],
            ['state' => 'Sokoto', 'lga' => 'Kware',          'latitude' => 13.0667, 'longitude' =>  5.5667],
            ['state' => 'Sokoto', 'lga' => 'Rabah',          'latitude' => 13.0667, 'longitude' =>  5.5500],
            ['state' => 'Sokoto', 'lga' => 'Sabon Birni',    'latitude' => 13.5833, 'longitude' =>  6.7333],
            ['state' => 'Sokoto', 'lga' => 'Shagari',        'latitude' => 12.5333, 'longitude' =>  4.8833],
            ['state' => 'Sokoto', 'lga' => 'Silame',         'latitude' => 13.1167, 'longitude' =>  4.8667],
            ['state' => 'Sokoto', 'lga' => 'Sokoto North',   'latitude' => 13.0622, 'longitude' =>  5.2339],
            ['state' => 'Sokoto', 'lga' => 'Sokoto South',   'latitude' => 13.0333, 'longitude' =>  5.2167],
            ['state' => 'Sokoto', 'lga' => 'Tambuwal',       'latitude' => 12.4000, 'longitude' =>  4.6333],
            ['state' => 'Sokoto', 'lga' => 'Tangaza',        'latitude' => 13.4000, 'longitude' =>  5.0000],
            ['state' => 'Sokoto', 'lga' => 'Tureta',         'latitude' => 12.7167, 'longitude' =>  5.3333],
            ['state' => 'Sokoto', 'lga' => 'Wamako',         'latitude' => 13.0833, 'longitude' =>  5.1333],
            ['state' => 'Sokoto', 'lga' => 'Wurno',          'latitude' => 13.2833, 'longitude' =>  5.4167],
            ['state' => 'Sokoto', 'lga' => 'Yabo',           'latitude' => 12.8667, 'longitude' =>  5.3333],

            // ----------------------------------------------------------------
            // TARABA
            // ----------------------------------------------------------------
            ['state' => 'Taraba', 'lga' => 'Ardo Kola',      'latitude' =>  8.9167, 'longitude' => 11.7833],
            ['state' => 'Taraba', 'lga' => 'Bali',           'latitude' =>  8.8667, 'longitude' => 11.5833],
            ['state' => 'Taraba', 'lga' => 'Donga',          'latitude' =>  7.9667, 'longitude' => 10.0000],
            ['state' => 'Taraba', 'lga' => 'Gashaka',        'latitude' =>  7.7500, 'longitude' => 11.4833],
            ['state' => 'Taraba', 'lga' => 'Gassol',         'latitude' =>  8.5333, 'longitude' => 10.5000],
            ['state' => 'Taraba', 'lga' => 'Ibi',            'latitude' =>  8.1833, 'longitude' =>  9.7333],
            ['state' => 'Taraba', 'lga' => 'Jalingo',        'latitude' =>  8.8978, 'longitude' => 11.3642],
            ['state' => 'Taraba', 'lga' => 'Karim Lamido',   'latitude' =>  9.0500, 'longitude' => 11.1833],
            ['state' => 'Taraba', 'lga' => 'Kurmi',          'latitude' =>  7.4833, 'longitude' => 10.7333],
            ['state' => 'Taraba', 'lga' => 'Lau',            'latitude' =>  9.2167, 'longitude' => 10.7000],
            ['state' => 'Taraba', 'lga' => 'Sardauna',       'latitude' =>  7.3000, 'longitude' => 11.7833],
            ['state' => 'Taraba', 'lga' => 'Takum',          'latitude' =>  7.2500, 'longitude' =>  9.9833],
            ['state' => 'Taraba', 'lga' => 'Ussa',           'latitude' =>  7.5667, 'longitude' => 10.0667],
            ['state' => 'Taraba', 'lga' => 'Wukari',         'latitude' =>  7.8667, 'longitude' =>  9.7833],
            ['state' => 'Taraba', 'lga' => 'Yorro',          'latitude' =>  8.6333, 'longitude' => 11.0500],
            ['state' => 'Taraba', 'lga' => 'Zing',           'latitude' =>  8.4500, 'longitude' => 11.7833],

            // ----------------------------------------------------------------
            // YOBE
            // ----------------------------------------------------------------
            ['state' => 'Yobe', 'lga' => 'Bade',             'latitude' => 12.7167, 'longitude' => 10.7833],
            ['state' => 'Yobe', 'lga' => 'Bursari',          'latitude' => 12.4000, 'longitude' => 11.5833],
            ['state' => 'Yobe', 'lga' => 'Damaturu',         'latitude' => 11.7472, 'longitude' => 11.9606],
            ['state' => 'Yobe', 'lga' => 'Fika',             'latitude' => 11.2167, 'longitude' => 11.2333],
            ['state' => 'Yobe', 'lga' => 'Fune',             'latitude' => 12.1167, 'longitude' => 11.9667],
            ['state' => 'Yobe', 'lga' => 'Geidam',           'latitude' => 12.8833, 'longitude' => 11.9333],
            ['state' => 'Yobe', 'lga' => 'Gujba',            'latitude' => 11.4167, 'longitude' => 12.1500],
            ['state' => 'Yobe', 'lga' => 'Gulani',           'latitude' => 11.1000, 'longitude' => 12.0667],
            ['state' => 'Yobe', 'lga' => 'Jakusko',          'latitude' => 12.1500, 'longitude' => 10.7167],
            ['state' => 'Yobe', 'lga' => 'Karasuwa',         'latitude' => 12.7500, 'longitude' => 10.5167],
            ['state' => 'Yobe', 'lga' => 'Machina',          'latitude' => 13.2167, 'longitude' => 10.8167],
            ['state' => 'Yobe', 'lga' => 'Nangere',          'latitude' => 11.9833, 'longitude' => 11.5667],
            ['state' => 'Yobe', 'lga' => 'Nguru',            'latitude' => 12.8833, 'longitude' => 10.4500],
            ['state' => 'Yobe', 'lga' => 'Potiskum',         'latitude' => 11.7000, 'longitude' => 11.0833],
            ['state' => 'Yobe', 'lga' => 'Tarmuwa',          'latitude' => 11.5833, 'longitude' => 11.8333],
            ['state' => 'Yobe', 'lga' => 'Yunusari',         'latitude' => 13.1000, 'longitude' => 11.1833],
            ['state' => 'Yobe', 'lga' => 'Yusufari',         'latitude' => 13.3333, 'longitude' => 11.5167],

            // ----------------------------------------------------------------
            // ZAMFARA
            // ----------------------------------------------------------------
            ['state' => 'Zamfara', 'lga' => 'Anka',          'latitude' => 12.0833, 'longitude' =>  5.9333],
            ['state' => 'Zamfara', 'lga' => 'Bakura',        'latitude' => 12.6667, 'longitude' =>  6.5333],
            ['state' => 'Zamfara', 'lga' => 'Birnin Magaji/Kiyaw','latitude' => 12.4500,'longitude' => 6.7333],
            ['state' => 'Zamfara', 'lga' => 'Bukkuyum',      'latitude' => 12.1000, 'longitude' =>  5.5167],
            ['state' => 'Zamfara', 'lga' => 'Bungudu',       'latitude' => 12.6500, 'longitude' =>  6.2333],
            ['state' => 'Zamfara', 'lga' => 'Gummi',         'latitude' => 12.1500, 'longitude' =>  5.1167],
            ['state' => 'Zamfara', 'lga' => 'Gusau',         'latitude' => 12.1696, 'longitude' =>  6.6649],
            ['state' => 'Zamfara', 'lga' => 'Kaura Namoda',  'latitude' => 12.5833, 'longitude' =>  6.5833],
            ['state' => 'Zamfara', 'lga' => 'Maradun',       'latitude' => 12.5833, 'longitude' =>  6.2833],
            ['state' => 'Zamfara', 'lga' => 'Maru',          'latitude' => 12.3500, 'longitude' =>  6.5667],
            ['state' => 'Zamfara', 'lga' => 'Shinkafi',      'latitude' => 13.0833, 'longitude' =>  6.4833],
            ['state' => 'Zamfara', 'lga' => 'Talata Mafara', 'latitude' => 12.5500, 'longitude' =>  6.0667],
            ['state' => 'Zamfara', 'lga' => 'Tsafe',         'latitude' => 12.3000, 'longitude' =>  7.0000],
            ['state' => 'Zamfara', 'lga' => 'Zurmi',         'latitude' => 12.7333, 'longitude' =>  6.8167],
        ];

        foreach ($lgas as $lga) {
            DB::table('lgaCoordinates')->updateOrInsert(
                [
                    'state' => $lga['state'],
                    'lga'   => $lga['lga'],
                ],
                array_merge($lga, [
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
            );
        }

        $this->command->info('LGA coordinates seeded: ' . count($lgas) . ' records.');
    }
}