<?php

namespace App\Services;

/**
 * Nigerian LGA Code Mapping Service
 * Provides unique 3-character codes for all Local Government Areas across Nigeria
 */
class LgaCodeMapping
{
    /**
     * Complete mapping of Nigerian States and their LGAs to unique 3-character codes
     * Format: State => [LGA Name => Code]
     */
    protected static array $lgaCodeMapping = [
        'Abia' => [
            'Aba North' => 'ABN',
            'Aba South' => 'ABS',
            'Arochukwu' => 'ARO',
            'Bende' => 'BEN',
            'Ikwuano' => 'IKW',
            'Isiala Ngwa North' => 'INN',
            'Isiala Ngwa South' => 'INS',
            'Isuikwuato' => 'ISU',
            'Obi Ngwa' => 'OBN',
            'Ohafia' => 'OHA',
            'Osisioma' => 'OSI',
            'Ugwunagbo' => 'UGW',
            'Ukwa East' => 'UKE',
            'Ukwa West' => 'UKW',
            'Umuahia North' => 'UMN',
            'Umuahia South' => 'UMS',
            'Umu Nneochi' => 'UNN',
        ],
        'Adamawa' => [
            'Demsa' => 'DEM',
            'Fufure' => 'FUF',
            'Ganye' => 'GAN',
            'Gayuk' => 'GAY',
            'Gombi' => 'GOM',
            'Grie' => 'GRI',
            'Hong' => 'HON',
            'Jada' => 'JAD',
            'Lamurde' => 'LAM',
            'Madagali' => 'MAD',
            'Maiha' => 'MAI',
            'Mayo Belwa' => 'MBE',
            'Michika' => 'MIC',
            'Mubi North' => 'MUN',
            'Mubi South' => 'MUS',
            'Numan' => 'NUM',
            'Shelleng' => 'SHE',
            'Song' => 'SON',
            'Toungo' => 'TOU',
            'Yola North' => 'YON',
            'Yola South' => 'YOS',
        ],
        'Akwa Ibom' => [
            'Abak' => 'ABA',
            'Eastern Obolo' => 'EOB',
            'Eket' => 'EKE',
            'Esit Eket' => 'ESE',
            'Essien Udim' => 'ESU',
            'Etim Ekpo' => 'ETE',
            'Etinan' => 'ETI',
            'Ibeno' => 'IBE',
            'Ibesikpo Asutan' => 'IBA',
            'Ibiono-Ibom' => 'IBI',
            'Ika' => 'IKA',
            'Ikono' => 'IKO',
            'Ikot Abasi' => 'IKA',
            'Ikot Ekpene' => 'IKE',
            'Ini' => 'INI',
            'Itu' => 'ITU',
            'Mbo' => 'MBO',
            'Mkpat-Enin' => 'MKP',
            'Nsit-Atai' => 'NSA',
            'Nsit-Ibom' => 'NSI',
            'Nsit-Ubium' => 'NSU',
            'Obot Akara' => 'OBA',
            'Okobo' => 'OKO',
            'Onna' => 'ONN',
            'Oron' => 'ORO',
            'Oruk Anam' => 'ORA',
            'Udung-Uko' => 'UDU',
            'Ukanafun' => 'UKA',
            'Uruan' => 'URU',
            'Urue-Offong/Oruko' => 'URO',
            'Uyo' => 'UYO',
        ],
        'Anambra' => [
            'Aguata' => 'AGU',
            'Anambra East' => 'ANE',
            'Anambra West' => 'ANW',
            'Anaocha' => 'ANA',
            'Awka North' => 'AWN',
            'Awka South' => 'AWS',
            'Ayamelum' => 'AYA',
            'Dunukofia' => 'DUN',
            'Ekwusigo' => 'EKW',
            'Idemili North' => 'IDN',
            'Idemili South' => 'IDS',
            'Ihiala' => 'IHI',
            'Njikoka' => 'NJI',
            'Nnewi North' => 'NNN',
            'Nnewi South' => 'NNS',
            'Ogbaru' => 'OGB',
            'Onitsha North' => 'ONN',
            'Onitsha South' => 'ONS',
            'Orumba North' => 'ORN',
            'Orumba South' => 'ORS',
            'Oyi' => 'OYI',
        ],
        'Bauchi' => [
            'Alkaleri' => 'ALK',
            'Bauchi' => 'BAU',
            'Bogoro' => 'BOG',
            'Damban' => 'DAM',
            'Darazo' => 'DAR',
            'Dass' => 'DAS',
            'Gamawa' => 'GAM',
            'Ganjuwa' => 'GAN',
            'Giade' => 'GIA',
            'Itas/Gadau' => 'ITA',
            'Jama\'are' => 'JAM',
            'Katagum' => 'KAT',
            'Kirfi' => 'KIR',
            'Misau' => 'MIS',
            'Ningi' => 'NIN',
            'Shira' => 'SHI',
            'Tafawa Balewa' => 'TAF',
            'Toro' => 'TOR',
            'Warji' => 'WAR',
            'Zaki' => 'ZAK',
        ],
        'Bayelsa' => [
            'Brass' => 'BRA',
            'Ekeremor' => 'EKE',
            'Kolokuma/Opokuma' => 'KOL',
            'Nembe' => 'NEM',
            'Ogbia' => 'OGB',
            'Sagbama' => 'SAG',
            'Southern Ijaw' => 'SIJ',
            'Yenagoa' => 'YEN',
        ],
        'Benue' => [
            'Ado' => 'ADO',
            'Agatu' => 'AGA',
            'Apa' => 'APA',
            'Buruku' => 'BUR',
            'Gboko' => 'GBO',
            'Guma' => 'GUM',
            'Gwer East' => 'GWE',
            'Gwer West' => 'GWW',
            'Katsina-Ala' => 'KAT',
            'Konshisha' => 'KON',
            'Kwande' => 'KWA',
            'Logo' => 'LOG',
            'Makurdi' => 'MAK',
            'Obi' => 'OBI',
            'Ogbadibo' => 'OGB',
            'Ohimini' => 'OHI',
            'Oju' => 'OJU',
            'Okpokwu' => 'OKP',
            'Oturkpo' => 'OTU',
            'Tarka' => 'TAR',
            'Ukum' => 'UKU',
            'Ushongo' => 'USH',
            'Vandeikya' => 'VAN',
        ],
        'Borno' => [
            'Abadam' => 'ABA',
            'Askira/Uba' => 'ASK',
            'Bama' => 'BAM',
            'Bayo' => 'BAY',
            'Biu' => 'BIU',
            'Chibok' => 'CHI',
            'Damboa' => 'DAM',
            'Dikwa' => 'DIK',
            'Gubio' => 'GUB',
            'Guzamala' => 'GUZ',
            'Gwoza' => 'GWO',
            'Hawul' => 'HAW',
            'Jere' => 'JER',
            'Kaga' => 'KAG',
            'Kala/Balge' => 'KAL',
            'Konduga' => 'KON',
            'Kukawa' => 'KUK',
            'Kwaya Kusar' => 'KWA',
            'Mafa' => 'MAF',
            'Magumeri' => 'MAG',
            'Maiduguri' => 'MAI',
            'Marte' => 'MAR',
            'Mobbar' => 'MOB',
            'Monguno' => 'MON',
            'Ngala' => 'NGA',
            'Nganzai' => 'NGZ',
            'Shani' => 'SHA',
        ],
        'Cross River' => [
            'Abi' => 'ABI',
            'Akamkpa' => 'AKA',
            'Akpabuyo' => 'AKP',
            'Bakassi' => 'BAK',
            'Bekwarra' => 'BEK',
            'Biase' => 'BIA',
            'Boki' => 'BOK',
            'Calabar Municipal' => 'CAM',
            'Calabar South' => 'CAS',
            'Etung' => 'ETU',
            'Ikom' => 'IKO',
            'Obanliku' => 'OBA',
            'Obubra' => 'OBU',
            'Obudu' => 'OBD',
            'Odukpani' => 'ODU',
            'Ogoja' => 'OGO',
            'Yakuur' => 'YAK',
            'Yala' => 'YAL',
        ],
        'Delta' => [
            'Aniocha North' => 'ANN',
            'Aniocha South' => 'ANS',
            'Bomadi' => 'BOM',
            'Burutu' => 'BUR',
            'Ethiope East' => 'ETE',
            'Ethiope West' => 'ETW',
            'Ika North East' => 'IKN',
            'Ika South' => 'IKS',
            'Isoko North' => 'ISN',
            'Isoko South' => 'ISS',
            'Ndokwa East' => 'NDE',
            'Ndokwa West' => 'NDW',
            'Okpe' => 'OKP',
            'Oshimili North' => 'OSN',
            'Oshimili South' => 'OSS',
            'Patani' => 'PAT',
            'Sapele' => 'SAP',
            'Udu' => 'UDU',
            'Ughelli North' => 'UGN',
            'Ughelli South' => 'UGS',
            'Ukwuani' => 'UKW',
            'Uvwie' => 'UVW',
            'Warri North' => 'WAN',
            'Warri South' => 'WAS',
            'Warri South West' => 'WSW',
        ],
        'Ebonyi' => [
            'Abakaliki' => 'ABA',
            'Afikpo North' => 'AFN',
            'Afikpo South' => 'AFS',
            'Ebonyi' => 'EBO',
            'Ezza North' => 'EZN',
            'Ezza South' => 'EZS',
            'Ikwo' => 'IKW',
            'Ishielu' => 'ISH',
            'Ivo' => 'IVO',
            'Izzi' => 'IZZ',
            'Ohaozara' => 'OHA',
            'Ohaukwu' => 'OHK',
            'Onicha' => 'ONI',
        ],
        'Edo' => [
            'Akoko-Edo' => 'AKO',
            'Egor' => 'EGO',
            'Esan Central' => 'ESC',
            'Esan North-East' => 'ENE',
            'Esan South-East' => 'ESE',
            'Esan West' => 'ESW',
            'Etsako Central' => 'ETC',
            'Etsako East' => 'ETE',
            'Etsako West' => 'ETW',
            'Igueben' => 'IGU',
            'Ikpoba Okha' => 'IKP',
            'Oredo' => 'ORE',
            'Orhionmwon' => 'ORH',
            'Ovia North-East' => 'OVN',
            'Ovia South-West' => 'OVS',
            'Owan East' => 'OWE',
            'Owan West' => 'OWW',
            'Uhunmwonde' => 'UHU',
        ],
        'Ekiti' => [
            'Ado Ekiti' => 'ADO',
            'Efon' => 'EFO',
            'Ekiti East' => 'EKE',
            'Ekiti South-West' => 'EKS',
            'Ekiti West' => 'EKW',
            'Emure' => 'EMU',
            'Gbonyin' => 'GBO',
            'Ido Osi' => 'IDO',
            'Ijero' => 'IJE',
            'Ikere' => 'IKE',
            'Ikole' => 'IKO',
            'Ilejemeje' => 'ILE',
            'Irepodun/Ifelodun' => 'IRE',
            'Ise/Orun' => 'ISE',
            'Moba' => 'MOB',
            'Oye' => 'OYE',
        ],
        'Enugu' => [
            'Aninri' => 'ANI',
            'Awgu' => 'AWG',
            'Enugu East' => 'ENE',
            'Enugu North' => 'ENN',
            'Enugu South' => 'ENS',
            'Ezeagu' => 'EZE',
            'Igbo Etiti' => 'IGE',
            'Igbo Eze North' => 'IGN',
            'Igbo Eze South' => 'IGS',
            'Isi Uzo' => 'ISI',
            'Nkanu East' => 'NKE',
            'Nkanu West' => 'NKW',
            'Nsukka' => 'NSU',
            'Oji River' => 'OJI',
            'Udenu' => 'UDE',
            'Udi' => 'UDI',
            'Uzo Uwani' => 'UZO',
        ],
        'FCT' => [
            'Abaji' => 'ABJ',
            'Abuja Municipal' => 'ABM',
            'Bwari' => 'BWA',
            'Gwagwalada' => 'GWA',
            'Kuje' => 'KUJ',
            'Kwali' => 'KWA',
        ],
        'Gombe' => [
            'Akko' => 'AKK',
            'Balanga' => 'BAL',
            'Billiri' => 'BIL',
            'Dukku' => 'DUK',
            'Funakaye' => 'FUN',
            'Gombe' => 'GOM',
            'Kaltungo' => 'KAL',
            'Kwami' => 'KWA',
            'Nafada' => 'NAF',
            'Shongom' => 'SHO',
            'Yamaltu/Deba' => 'YAM',
        ],
        'Imo' => [
            'Aboh Mbaise' => 'ABM',
            'Ahiazu Mbaise' => 'AHM',
            'Ehime Mbano' => 'EHI',
            'Ezinihitte' => 'EZI',
            'Ideato North' => 'IDN',
            'Ideato South' => 'IDS',
            'Ihitte/Uboma' => 'IHI',
            'Ikeduru' => 'IKE',
            'Isiala Mbano' => 'ISM',
            'Isu' => 'ISU',
            'Mbaitoli' => 'MBA',
            'Ngor Okpala' => 'NGO',
            'Njaba' => 'NJA',
            'Nkwerre' => 'NKW',
            'Nwangele' => 'NWA',
            'Obowo' => 'OBO',
            'Oguta' => 'OGU',
            'Ohaji/Egbema' => 'OHA',
            'Okigwe' => 'OKI',
            'Orlu' => 'ORL',
            'Orsu' => 'ORS',
            'Oru East' => 'ORE',
            'Oru West' => 'ORW',
            'Owerri Municipal' => 'OWM',
            'Owerri North' => 'OWN',
            'Owerri West' => 'OWW',
            'Unuimo' => 'UNU',
        ],
        'Jigawa' => [
            'Auyo' => 'AUY',
            'Babura' => 'BAB',
            'Biriniwa' => 'BIR',
            'Birnin Kudu' => 'BKU',
            'Buji' => 'BUJ',
            'Dutse' => 'DUT',
            'Gagarawa' => 'GAG',
            'Garki' => 'GAR',
            'Gumel' => 'GUM',
            'Guri' => 'GUR',
            'Gwaram' => 'GWA',
            'Gwiwa' => 'GWI',
            'Hadejia' => 'HAD',
            'Jahun' => 'JAH',
            'Kafin Hausa' => 'KAF',
            'Kazaure' => 'KAZ',
            'Kiri Kasama' => 'KIR',
            'Kiyawa' => 'KIY',
            'Kaugama' => 'KAU',
            'Maigatari' => 'MAI',
            'Malam Madori' => 'MAL',
            'Miga' => 'MIG',
            'Ringim' => 'RIN',
            'Roni' => 'RON',
            'Sule Tankarkar' => 'SUL',
            'Taura' => 'TAU',
            'Yankwashi' => 'YAN',
        ],
        'Kaduna' => [
            'Birnin Gwari' => 'BIG',
            'Chikun' => 'CHI',
            'Giwa' => 'GIW',
            'Igabi' => 'IGA',
            'Ikara' => 'IKA',
            'Jaba' => 'JAB',
            'Jema\'a' => 'JEM',
            'Kachia' => 'KAC',
            'Kaduna North' => 'KDN',
            'Kaduna South' => 'KDS',
            'Kagarko' => 'KAG',
            'Kajuru' => 'KAJ',
            'Kaura' => 'KAU',
            'Kauru' => 'KRU',
            'Kubau' => 'KUB',
            'Kudan' => 'KUD',
            'Lere' => 'LER',
            'Makarfi' => 'MAK',
            'Sabon Gari' => 'SAB',
            'Sanga' => 'SAN',
            'Soba' => 'SOB',
            'Zangon Kataf' => 'ZAN',
            'Zaria' => 'ZAR',
        ],
        'Kano' => [
            'Ajingi' => 'AJI',
            'Albasu' => 'ALB',
            'Bagwai' => 'BAG',
            'Bebeji' => 'BEB',
            'Bichi' => 'BIC',
            'Bunkure' => 'BUN',
            'Dala' => 'DAL',
            'Dambatta' => 'DAM',
            'Dawakin Kudu' => 'DKU',
            'Dawakin Tofa' => 'DTO',
            'Doguwa' => 'DOG',
            'Fagge' => 'FAG',
            'Gabasawa' => 'GAB',
            'Garko' => 'GAR',
            'Garun Mallam' => 'GMA',
            'Gaya' => 'GAY',
            'Gezawa' => 'GEZ',
            'Gwale' => 'GWA',
            'Gwarzo' => 'GWZ',
            'Kabo' => 'KAB',
            'Kano Municipal' => 'KNM',
            'Karaye' => 'KAR',
            'Kibiya' => 'KIB',
            'Kiru' => 'KIR',
            'Kumbotso' => 'KUM',
            'Kunchi' => 'KUN',
            'Kura' => 'KUR',
            'Madobi' => 'MAD',
            'Makoda' => 'MAK',
            'Minjibir' => 'MIN',
            'Nasarawa' => 'NAS',
            'Rano' => 'RAN',
            'Rimin Gado' => 'RIM',
            'Rogo' => 'ROG',
            'Shanono' => 'SHA',
            'Sumaila' => 'SUM',
            'Takai' => 'TAK',
            'Tarauni' => 'TAR',
            'Tofa' => 'TOF',
            'Tsanyawa' => 'TSA',
            'Tudun Wada' => 'TUD',
            'Ungogo' => 'UNG',
            'Warawa' => 'WAR',
            'Wudil' => 'WUD',
        ],
        'Katsina' => [
            'Bakori' => 'BAK',
            'Batagarawa' => 'BAT',
            'Batsari' => 'BTS',
            'Baure' => 'BAU',
            'Bindawa' => 'BIN',
            'Charanchi' => 'CHA',
            'Dandume' => 'DAN',
            'Danja' => 'DNJ',
            'Dan Musa' => 'DMS',
            'Daura' => 'DAU',
            'Dutsi' => 'DUT',
            'Dutsin Ma' => 'DMA',
            'Faskari' => 'FAS',
            'Funtua' => 'FUN',
            'Ingawa' => 'ING',
            'Jibia' => 'JIB',
            'Kafur' => 'KAF',
            'Kaita' => 'KAI',
            'Kankara' => 'KAN',
            'Kankia' => 'KNK',
            'Katsina' => 'KAT',
            'Kurfi' => 'KUR',
            'Kusada' => 'KUS',
            'Mai\'Adua' => 'MAI',
            'Malumfashi' => 'MAL',
            'Mani' => 'MAN',
            'Mashi' => 'MAS',
            'Matazu' => 'MAT',
            'Musawa' => 'MUS',
            'Rimi' => 'RIM',
            'Sabuwa' => 'SAB',
            'Safana' => 'SAF',
            'Sandamu' => 'SAN',
            'Zango' => 'ZAN',
        ],
        'Kebbi' => [
            'Aleiro' => 'ALE',
            'Arewa Dandi' => 'ARD',
            'Argungu' => 'ARG',
            'Augie' => 'AUG',
            'Bagudo' => 'BAG',
            'Birnin Kebbi' => 'BKE',
            'Bunza' => 'BUN',
            'Dandi' => 'DAN',
            'Fakai' => 'FAK',
            'Gwandu' => 'GWA',
            'Jega' => 'JEG',
            'Kalgo' => 'KAL',
            'Koko/Besse' => 'KOK',
            'Maiyama' => 'MAI',
            'Ngaski' => 'NGA',
            'Sakaba' => 'SAK',
            'Shanga' => 'SHA',
            'Suru' => 'SUR',
            'Wasagu/Danko' => 'WAS',
            'Yauri' => 'YAU',
            'Zuru' => 'ZUR',
        ],
        'Kogi' => [
            'Adavi' => 'ADA',
            'Ajaokuta' => 'AJA',
            'Ankpa' => 'ANK',
            'Bassa' => 'BAS',
            'Dekina' => 'DEK',
            'Ibaji' => 'IBA',
            'Idah' => 'IDA',
            'Igalamela Odolu' => 'IGO',
            'Ijumu' => 'IJU',
            'Kabba/Bunu' => 'KAB',
            'Kogi' => 'KOG',
            'Lokoja' => 'LOK',
            'Mopa Muro' => 'MOP',
            'Ofu' => 'OFU',
            'Ogori/Magongo' => 'OGO',
            'Okehi' => 'OKE',
            'Okene' => 'OKN',
            'Olamaboro' => 'OLA',
            'Omala' => 'OMA',
            'Yagba East' => 'YAE',
            'Yagba West' => 'YAW',
        ],
        'Kwara' => [
            'Asa' => 'ASA',
            'Baruten' => 'BAR',
            'Edu' => 'EDU',
            'Ekiti' => 'EKI',
            'Ifelodun' => 'IFE',
            'Ilorin East' => 'ILE',
            'Ilorin South' => 'ILS',
            'Ilorin West' => 'ILW',
            'Irepodun' => 'IRE',
            'Isin' => 'ISI',
            'Kaiama' => 'KAI',
            'Moro' => 'MOR',
            'Offa' => 'OFF',
            'Oke Ero' => 'OKE',
            'Oyun' => 'OYU',
            'Pategi' => 'PAT',
        ],
        'Lagos' => [
            'Agege' => 'AGE',
            'Ajeromi-Ifelodun' => 'AJE',
            'Alimosho' => 'ALI',
            'Amuwo-Odofin' => 'AMU',
            'Apapa' => 'APA',
            'Badagry' => 'BAD',
            'Epe' => 'EPE',
            'Eti Osa' => 'ETO',
            'Ibeju-Lekki' => 'IBE',
            'Ifako-Ijaiye' => 'IFA',
            'Ikeja' => 'IKE',
            'Ikorodu' => 'IKO',
            'Kosofe' => 'KOS',
            'Lagos Island' => 'LAI',
            'Lagos Mainland' => 'LAM',
            'Mushin' => 'MUS',
            'Ojo' => 'OJO',
            'Oshodi-Isolo' => 'OSH',
            'Shomolu' => 'SHO',
            'Surulere' => 'SUR',
        ],
        'Nasarawa' => [
            'Akwanga' => 'AKW',
            'Awe' => 'AWE',
            'Doma' => 'DOM',
            'Karu' => 'KAR',
            'Keana' => 'KEA',
            'Keffi' => 'KEF',
            'Kokona' => 'KOK',
            'Lafia' => 'LAF',
            'Nasarawa' => 'NAS',
            'Nasarawa Egon' => 'NAE',
            'Obi' => 'OBI',
            'Toto' => 'TOT',
            'Wamba' => 'WAM',
        ],
        'Niger' => [
            'Agaie' => 'AGA',
            'Agwara' => 'AGW',
            'Bida' => 'BID',
            'Borgu' => 'BOR',
            'Bosso' => 'BOS',
            'Chanchaga' => 'CHA',
            'Edati' => 'EDA',
            'Gbako' => 'GBA',
            'Gurara' => 'GUR',
            'Katcha' => 'KAT',
            'Kontagora' => 'KON',
            'Lapai' => 'LAP',
            'Lavun' => 'LAV',
            'Magama' => 'MAG',
            'Mariga' => 'MAR',
            'Mashegu' => 'MAS',
            'Mokwa' => 'MOK',
            'Moya' => 'MOY',
            'Paikoro' => 'PAI',
            'Rafi' => 'RAF',
            'Rijau' => 'RIJ',
            'Shiroro' => 'SHI',
            'Suleja' => 'SUL',
            'Tafa' => 'TAF',
            'Wushishi' => 'WUS',
        ],
        'Ogun' => [
            'Abeokuta North' => 'ABN',
            'Abeokuta South' => 'ABS',
            'Ado-Odo/Ota' => 'ADO',
            'Egbado North' => 'EGN',
            'Egbado South' => 'EGS',
            'Ewekoro' => 'EWE',
            'Ifo' => 'IFO',
            'Ijebu East' => 'IJE',
            'Ijebu North' => 'IJN',
            'Ijebu North East' => 'INE',
            'Ijebu Ode' => 'IJO',
            'Ikenne' => 'IKE',
            'Imeko Afon' => 'IME',
            'Ipokia' => 'IPO',
            'Obafemi Owode' => 'OBA',
            'Odeda' => 'ODE',
            'Odogbolu' => 'ODO',
            'Ogun Waterside' => 'OGW',
            'Remo North' => 'REN',
            'Shagamu' => 'SHA',
        ],
        'Ondo' => [
            'Akoko North-East' => 'ANE',
            'Akoko North-West' => 'ANW',
            'Akoko South-West' => 'ASW',
            'Akoko South-East' => 'ASE',
            'Akure North' => 'AKN',
            'Akure South' => 'AKS',
            'Ese Odo' => 'ESE',
            'Idanre' => 'IDA',
            'Ifedore' => 'IFE',
            'Ilaje' => 'ILA',
            'Ile Oluji/Okeigbo' => 'ILO',
            'Irele' => 'IRE',
            'Odigbo' => 'ODI',
            'Okitipupa' => 'OKI',
            'Ondo East' => 'ONE',
            'Ondo West' => 'ONW',
            'Ose' => 'OSE',
            'Owo' => 'OWO',
        ],
        'Osun' => [
            'Atakunmosa East' => 'ATE',
            'Atakunmosa West' => 'ATW',
            'Aiyedaade' => 'AIY',
            'Aiyedire' => 'AYD',
            'Boluwaduro' => 'BOL',
            'Boripe' => 'BOR',
            'Ede North' => 'EDN',
            'Ede South' => 'EDS',
            'Ife Central' => 'IFC',
            'Ife East' => 'IFE',
            'Ife North' => 'IFN',
            'Ife South' => 'IFS',
            'Egbedore' => 'EGB',
            'Ejigbo' => 'EJI',
            'Ifedayo' => 'IFD',
            'Ifelodun' => 'IFL',
            'Ila' => 'ILA',
            'Ilesa East' => 'ILE',
            'Ilesa West' => 'ILW',
            'Irepodun' => 'IRE',
            'Irewole' => 'IRW',
            'Isokan' => 'ISO',
            'Iwo' => 'IWO',
            'Obokun' => 'OBO',
            'Odo Otin' => 'ODO',
            'Ola Oluwa' => 'OLA',
            'Olorunda' => 'OLO',
            'Oriade' => 'ORI',
            'Orolu' => 'ORL',
            'Osogbo' => 'OSO',
        ],
        'Oyo' => [
            'Afijio' => 'AFI',
            'Akinyele' => 'AKI',
            'Atiba' => 'ATI',
            'Atisbo' => 'ATS',
            'Egbeda' => 'EGB',
            'Ibadan North' => 'IBN',
            'Ibadan North-East' => 'INE',
            'Ibadan North-West' => 'INW',
            'Ibadan South-East' => 'ISE',
            'Ibadan South-West' => 'ISW',
            'Ibarapa Central' => 'IBC',
            'Ibarapa East' => 'IBE',
            'Ibarapa North' => 'IBA',
            'Ido' => 'IDO',
            'Irepo' => 'IRE',
            'Iseyin' => 'ISE',
            'Itesiwaju' => 'ITE',
            'Iwajowa' => 'IWA',
            'Kajola' => 'KAJ',
            'Lagelu' => 'LAG',
            'Ogbomosho North' => 'OGN',
            'Ogbomosho South' => 'OGS',
            'Ogo Oluwa' => 'OGO',
            'Olorunsogo' => 'OLO',
            'Oluyole' => 'OLU',
            'Ona Ara' => 'ONA',
            'Orelope' => 'ORL',
            'Ori Ire' => 'ORI',
            'Oyo' => 'OYO',
            'Oyo East' => 'OYE',
            'Saki East' => 'SAE',
            'Saki West' => 'SAW',
            'Surulere' => 'SUR',
        ],
        'Plateau' => [
            'Barkin Ladi' => 'BAR',
            'Bassa' => 'BAS',
            'Bokkos' => 'BOK',
            'Jos East' => 'JEA',
            'Jos North' => 'JNO',
            'Jos South' => 'JSO',
            'Kanam' => 'KAN',
            'Kanke' => 'KNK',
            'Langtang North' => 'LAN',
            'Langtang South' => 'LAS',
            'Mangu' => 'MAN',
            'Mikang' => 'MIK',
            'Pankshin' => 'PAN',
            'Qua\'an Pan' => 'QUA',
            'Riyom' => 'RIY',
            'Shendam' => 'SHE',
            'Wase' => 'WAS',
        ],
        'Rivers' => [
            'Abua/Odual' => 'ABO',
            'Ahoada East' => 'AHE',
            'Ahoada West' => 'AHW',
            'Akuku-Toru' => 'AKU',
            'Andoni' => 'AND',
            'Asari-Toru' => 'ASA',
            'Bonny' => 'BON',
            'Degema' => 'DEG',
            'Eleme' => 'ELE',
            'Emuoha' => 'EMU',
            'Etche' => 'ETC',
            'Gokana' => 'GOK',
            'Ikwerre' => 'IKW',
            'Khana' => 'KHA',
            'Obio/Akpor' => 'OBI',
            'Ogba/Egbema/Ndoni' => 'OGE',
            'Ogu/Bolo' => 'OGU',
            'Okrika' => 'OKR',
            'Omuma' => 'OMU',
            'Opobo/Nkoro' => 'OPO',
            'Oyigbo' => 'OYI',
            'Port Harcourt' => 'PHC',
            'Tai' => 'TAI',
        ],
        'Sokoto' => [
            'Binji' => 'BIN',
            'Bodinga' => 'BOD',
            'Dange Shuni' => 'DAN',
            'Gada' => 'GAD',
            'Goronyo' => 'GOR',
            'Gudu' => 'GUD',
            'Gwadabawa' => 'GWA',
            'Illela' => 'ILL',
            'Isa' => 'ISA',
            'Kebbe' => 'KEB',
            'Kware' => 'KWA',
            'Rabah' => 'RAB',
            'Sabon Birni' => 'SAB',
            'Shagari' => 'SHA',
            'Silame' => 'SIL',
            'Sokoto North' => 'SON',
            'Sokoto South' => 'SOS',
            'Tambuwal' => 'TAM',
            'Tangaza' => 'TAN',
            'Tureta' => 'TUR',
            'Wamako' => 'WAM',
            'Wurno' => 'WUR',
            'Yabo' => 'YAB',
        ],
        'Taraba' => [
            'Ardo Kola' => 'ARD',
            'Bali' => 'BAL',
            'Donga' => 'DON',
            'Gashaka' => 'GAS',
            'Gassol' => 'GSL',
            'Ibi' => 'IBI',
            'Jalingo' => 'JAL',
            'Karim Lamido' => 'KAR',
            'Kumi' => 'KUM',
            'Lau' => 'LAU',
            'Sardauna' => 'SAR',
            'Takum' => 'TAK',
            'Ussa' => 'USS',
            'Wukari' => 'WUK',
            'Yorro' => 'YOR',
            'Zing' => 'ZIN',
        ],
        'Yobe' => [
            'Bade' => 'BAD',
            'Bursari' => 'BUR',
            'Damaturu' => 'DAM',
            'Fika' => 'FIK',
            'Fune' => 'FUN',
            'Geidam' => 'GEI',
            'Gujba' => 'GUJ',
            'Gulani' => 'GUL',
            'Jakusko' => 'JAK',
            'Karasuwa' => 'KAR',
            'Machina' => 'MAC',
            'Nangere' => 'NAN',
            'Nguru' => 'NGU',
            'Potiskum' => 'POT',
            'Tarmuwa' => 'TAR',
            'Yunusari' => 'YUN',
            'Yusufari' => 'YUS',
        ],
        'Zamfara' => [
            'Anka' => 'ANK',
            'Bakura' => 'BAK',
            'Birnin Magaji/Kiyaw' => 'BIM',
            'Bukkuyum' => 'BUK',
            'Bungudu' => 'BUN',
            'Gummi' => 'GUM',
            'Gusau' => 'GUS',
            'Kaura Namoda' => 'KAN',
            'Maradun' => 'MAR',
            'Maru' => 'MRU',
            'Shinkafi' => 'SHI',
            'Talata Mafara' => 'TAL',
            'Chafe' => 'CHA',
            'Zurmi' => 'ZUR',
        ],
    ];

    /**
     * Get the unique LGA code for a given state and LGA
     *
     * @param string $state The state name
     * @param string $lga The LGA name
     * @return string The 3-character LGA code, or first 3 chars as fallback
     */
    public static function getLgaCode(string $state, string $lga): string
    {
        // Check if the state exists in our mapping
        if (isset(self::$lgaCodeMapping[$state])) {
            // Check if the LGA exists for this state
            if (isset(self::$lgaCodeMapping[$state][$lga])) {
                return self::$lgaCodeMapping[$state][$lga];
            }
        }

        // Fallback: return first 3 characters (uppercase, no spaces)
        $cleanLga = strtoupper(str_replace(' ', '', $lga));
        return substr($cleanLga, 0, 3);
    }

    /**
     * Get all LGAs for a given state
     *
     * @param string $state The state name
     * @return array Array of LGA names for the state
     */
    public static function getLgasForState(string $state): array
    {
        return array_keys(self::$lgaCodeMapping[$state] ?? []);
    }

    /**
     * Get all states
     *
     * @return array Array of all state names
     */
    public static function getAllStates(): array
    {
        return array_keys(self::$lgaCodeMapping);
    }

    /**
     * Verify if a state-LGA combination exists
     *
     * @param string $state The state name
     * @param string $lga The LGA name
     * @return bool True if the combination exists
     */
    public static function isValidStateLgaCombination(string $state, string $lga): bool
    {
        return isset(self::$lgaCodeMapping[$state][$lga]);
    }

    /**
     * Get the full mapping array (for export/debugging)
     *
     * @return array The complete LGA code mapping
     */
    public static function getFullMapping(): array
    {
        return self::$lgaCodeMapping;
    }
}